ssh_defaults:
  options:
    - ServerAliveInterval 30
    - ServerAliveCountMax 3
    - TCPKeepAlive true
  device:
    - server
    - asus
    - honor
    - wslasus
    - wslhonor

sshkeys: "{{ homedir }}/.ssh"
ssh_hosts:
  nuc:
    hostname: "{{ wireguard_server_ip }}"
    user: "{{ user }}"
    identity: nuc_server
    device:
      - asus
      - honor
      - wslasus
      - wslhonor

  github.com:
    hostname: github.com
    user: git
    identity: github
    device:
      - server
      - asus
      - honor
      - wslasus
      - wslhonor

  redmi:
    hostname: "{{ wireguard_devices.phone.ip }}"
    port: "{{ termux_port }}"
    user: "{{ termux.redmi.user }}"
    identity: "{{ termux.redmi.key }}"
    device:
      - server
      - asus
      - honor
      - wslasus

  asus-lan:
    hostname: "{{ lan_ip.large_laptop }}"
    user: "\"{{ whost.asus.user }}\""
    identity: asus_k95vb
    device:
      - honor

  asus-vpn:
    hostname: "{{ wireguard_devices.large_laptop.ip }}"
    user: "\"{{ whost.asus.user }}\""
    identity: asus_k95vb
    device:
      - honor
  
  ds209:
    hostname: "{{ lan_ip.diskstation }}"
    user: admin
    identity: ds209
    options:
      - PubkeyAcceptedAlgorithms +ssh-rsa
      - HostKeyAlgorithms +ssh-rsa
    device:
      - server
      - wslasus

  honor-lan:
    hostname: "{{ lan_ip.small_laptop }}"
    user: "{{ whost.honor.user }}"
    identity: honor_magicbook
    device:
      - asus

  honor-vpn:
    hostname: "{{ wireguard_devices.laptop.ip }}"
    user: "{{ whost.honor.user }}"
    identity: honor_magicbook
    device:
      - asus

  icl:
    hostname: "{{ lan_ip.icl_srv }}"
    user: "{{ user }}"
    identity: icl_server
    device:
      - server
      - honor
      - asus
      # - wslasus #key moved to c:

  # Ubiquiti EdgeRouter Lite (ERLite-3)
  router:
    hostname: "{{ lan_ip.router }}"
    user: ubnt
    identity: router
    device:
      - server
      - asus
      # - wslasus #key moved to c:
      - wslhonor

  samsung:
    hostname: "{{ wireguard_devices.pad.ip }}"
    port: "{{ termux_port }}"
    user: "{{ termux.samsung.user }}"
    identity: "{{ termux.samsung.key }}"
    path: /storage/0123-4567/
    device:
      - server

  smarttv:
    hostname: "{{ wireguard_devices.x96q.ip }}"
    port: "{{ termux_port }}"
    user: "{{ termux.x96q.user }}"
    identity: "{{ termux.x96q.key }}"
    device:
      - server

  repos.21-school.ru:
    hostname: repos-ssh.21-school.ru
    user: git
    identity: s21
    device:
      - wslasus
