- name: daemon reload
  systemd:
    daemon_reload: yes

- name: restart services
  systemd:
    name: "{{ item | basename | regex_replace('.service','') }}"
    enabled: yes
    state: restarted
  with_fileglob:
    - "files/systemd/*.service"

- name: ensure wireguard logs directory exists
  file:
    path: "{{ wireguard_connections_log | dirname }}"
    state: directory

- name: ensure geo ip cache directory exists
  file:
    path: "{{ geo_ip_cache }}"
    state: directory

- name: ensure telegram bot log directory exists
  file:
    path: "{{ telegram_bot_log }}"
    state: directory