- name: daemon reload
  systemd:
    daemon_reload: yes

- name: reload overrided services
  systemd:
    name: "{{ item }}"
    state: reloaded
  loop: "{{ service_override }}"

- name: restart services
  systemd:
    name: "{{ item | basename | regex_replace('.j2','') | regex_replace('.service','') }}"
    enabled: yes
    state: restarted
  with_fileglob:
    - "templates/systemd/*.service"
    - "templates/systemd/*.service.j2"

- name: ensure custom logs directories exist
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ telegram_bot_logs }}"
    - "{{ geo_ip_cache }}"
    - "{{ wireguard_connections_log | dirname }}"
    - "{{ container_notifications_log | dirname }}"
    - "{{ service_notifications_log | dirname }}"
  notify: daemon reload
