[Definition]

actionban = /usr/local/bin/f2b-notifications.sh "<name>" "<ip>" "<logpath>" "{{ fail2ban_bantime }}" "<failures>" "<ipfailures>" "<ipjailfailures>"
actionunban =
# actionunban = /usr/local/bin/tgbot_notify.sh "<b><name></b>: unbanned <ip> from <fq-hostname>"

[Init]
name = telegram
