- name: Install nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Enable nginx
  systemd:
    name: nginx
    enabled: yes
    state: started

- name: Deploy nginx config
  copy:
    src: nginx.conf
    dest: /etc/nginx
  notify: validate and reload nginx

- name: Deploy nginx sites
  template:
    src: site.j2
    dest: "/etc/nginx/sites-available/{{ item.server_name }}"
  loop: "{{ nginx_sites }}"
  notify: validate and reload nginx

- name: Enable sites
  file:
    src: "/etc/nginx/sites-available/{{ item.server_name }}"
    dest: "/etc/nginx/sites-enabled/{{ item.server_name }}"
    state: link
  loop: "{{ nginx_sites }}"

- name: Replace cockpit motd
  template:
    src: cockpit.active.issue.j2
    dest: "/run/cockpit/active.issue"