- name: Install nginx
  apt:
    name:
      - nginx
      - libnginx-mod-stream
    state: present
    update_cache: yes

- name: Enable nginx
  systemd:
    name: nginx
    enabled: yes
    state: started

- name: Deploy nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: validate and reload nginx

- name: Deploy public nginx sites
  template:
    src: public.j2
    dest: "/etc/nginx/sites-available/{{ item }}"
  loop: "{{ nginx_public_sites }}"
  notify: validate and reload nginx

- name: Enable public sites
  file:
    src: "/etc/nginx/sites-available/{{ item }}"
    dest: "/etc/nginx/sites-enabled/{{ item }}"
    state: link
  loop: "{{ nginx_public_sites }}"

- name: Deploy private nginx sites
  template:
    src: private.j2
    dest: "/etc/nginx/sites-available/{{ item.key }}.{{ domain }}"
  loop: "{{ nginx_private_sites | dict2items }}"
  notify: validate and reload nginx

- name: Enable private sites
  file:
    src: "/etc/nginx/sites-available/{{ item.key }}.{{ domain }}"
    dest: "/etc/nginx/sites-enabled/{{ item.key }}.{{ domain }}"
    state: link
  loop: "{{ nginx_private_sites | dict2items }}"

- name: Deploy localhost sites
  template:
    src: "{{ item }}"
    dest: "/etc/nginx/sites-available/{{ item | basename | regex_replace('.j2','') }}"
  with_fileglob:
    - templates/localsites/*.j2
  notify: validate and reload nginx

- name: Enable localhost sites
  file:
    src: "/etc/nginx/sites-available/{{ item | basename | regex_replace('.j2','') }}"
    dest: "/etc/nginx/sites-enabled/{{ item | basename | regex_replace('.j2','') }}"
    state: link
  with_fileglob:
    - templates/localsites/*.j2
