- name: Install git and delta
  become: false
  homebrew:
    name: "{{ item }}"
    state: present
    update_homebrew: true
  loop:
    - git
    - git-delta
    # macos may require also 'less' as well as windows

- name: Deploy gitconfig
  template:
    src: gitconfig.j2
    dest: "{{ homedir }}/.gitconfig"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0644'
