docker_relabel:
  container_name:
    source: __meta_docker_container_name
    target: container
  log_stream:
    source: __meta_docker_container_log_stream
    target: stream
  docker_compose_service:
    source: __meta_docker_container_label_com_docker_compose_service
    target: service
