geoip_labeldrop:
  - geoip_city_name
  - geoip_continent_code
  - geoip_continent_name
  - geoip_location_latitude
  - geoip_location_longitude
  - geoip_postal_code
  - geoip_subdivision_code
  - geoip_subdivision_name
  - geoip_timezone
