- name: Install Cockpit
  apt:
    name: cockpit
    state: present
    update_cache: yes

- name: Create override dirs
  file:
    path: "{{ systemd_services }}/cockpit.socket.d"
    state: directory
    mode: '0755'

- name: Deploy socket override
  template:
    src: override.conf.j2
    dest: "{{ systemd_services }}/cockpit.socket.d/override.conf"
  notify:
    - daemon reload
    - restart cockpit socket

- name: Enable cockpit
  systemd:
    name: cockpit
    enabled: yes
    state: started

- name: Remove cockpit motd
  file:
    path: /etc/issue.d/cockpit.issue
    state: absent

- name: Disable cockpit issue
  file:
    src: /dev/null
    dest: /run/cockpit/issue
    state: link
    force: yes
