- name: Install Cockpit
  apt:
    name: cockpit
    state: present
    update_cache: yes

- import_tasks: cert.yml
  when: cockpit_generate_cert

- name: Enable cockpit
  systemd:
    name: cockpit
    enabled: yes
    state: started