- hosts: server
  become: yes

  pre_tasks:
    - name: Check OS family
      assert:
        that: ansible_os_family == "Debian"
        fail_msg: "This playbook supports only Debian-based systems"
    - name: Fail if unknown tag is used
      tags: always
      assert:
        that: ansible_run_tags | difference(valid_tags + ['all']) | length == 0
        fail_msg: "Unknown tag used: {{ ansible_run_tags | difference(valid_tags + ['all']) }}"
      vars:
        valid_tags: "{{ roles_list }}"

  vars_files:
    - group_vars/all/vault.yml

  vars:
    roles_list:
      - base
      - etckeeper
      - auditd
      - sysctl
      - sshd
      - ssh_client
      - wireguard
      - firewall
      - nginx
      - fail2ban
      - crowdsec
      - dnsmasq
      - letsencrypt
      - logrotate
      - samba
      - mount_diskstation
      - mount_android
      - mail_sender
      - notifications
      - cockpit
      - vim
      - zsh
      - docker

  tasks:
    - name: Include roles dynamically
      include_role:
        name: "{{ role_item }}"
        apply:
          tags: "{{ role_item }}"
      loop: "{{ roles_list }}"
      loop_control:
        loop_var: role_item
      tags:
        - always
