allowed_countries:
  - Russia

allowed_regions:
  - Tatarstan Republic

allowed_asn:
  - AS12389 PJSC Rostelecom
  - AS16345 PJSC \"Vimpelcom\"

allowed_subnets:
  - "{{ home_network }}"
  - "{{ wireguard_network }}"
  - "{{ home_ip }}/32"