sshd_log: /var/log/auth.log
wireguard_connections_log: /var/log/wireguard/{{ wireguard_interface }}_connections.log
telegram_bot_logs: /var/log/telegram
geo_ip_cache: /var/cache/telegram/
telegram_bot_error_log: "{{ telegram_bot_logs }}/message_error.log"
telegram_bot_success_log: "{{ telegram_bot_logs }}/message_success.log"

allowed_countries:
  - Russia

allowed_regions:
  - Tatarstan Republic

allowed_asn:
  - AS12389 PJSC Rostelecom
  - AS16345 PJSC \"Vimpelcom\"

allowed_subnets:
  - "{{ home_network }}"
  - "{{ wireguard_network }}"
  - "{{ home_ip }}/32"