ping_retry_command: "for i in {1..30}; do ping -c1 8.8.8.8 && break; sleep 5; done;"
nc_retry_command: "for i in {1..30}; do nc -zv {{ localhost }} {{ socks5_port }} && break; sleep 2; done;"

service_state:
  - "wg-quick@{{ wireguard_interface }}"
  - nftables
  - nginx
  - fail2ban
  - crowdsec
  - dnsmasq
  - smbd
  - docker
