#may not be needed if docker-container-watcher.service.j2 is better

# - name: Deploy notifier container docker-compose
#   template:
#     src: templates/containers/docker-compose.yml.j2
#     dest: "{{ container_dir }}/docker-compose.yml"

# - name: Run notifier container
#   community.docker.docker_compose_v2:
#     project_src: "{{ container_dir }}"
#     state: present
#     recreate: always

- name: Run notifier container
  community.docker.docker_container:
    name: sidecar-notifier
    image: docker:cli
    restart_policy: unless-stopped
    recreate: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "{{ telegram_script }}:{{ container_telegram }}:ro"
      - "{{ docker_watcher_script }}:/watcher.sh:ro"
    entrypoint: ["/bin/sh", "/watcher.sh"]

- name: Get notifier container info
  community.docker.docker_container_info:
    name: sidecar-notifier
  register: notifier_info

- name: Fail if the container is not running
  fail:
    msg: "Notifier container is not running"
  when: not notifier_info.container.State.Running
