- name: Load values
  include_vars: "{{ item }}"
  with_fileglob:
    - defaults/*.yml

- name: Ensure scripts directory exists
  file:
    path: "{{ scripts_dir }}/{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - ""
    - "includes"

- name: Deploy scripts
  template:
    src: "{{ item }}"
    dest: "{{ scripts_dir }}/{{ item | basename | regex_replace('.j2','') }}"
    mode: '0755'
  with_fileglob:
    - "templates/scripts/*.j2"
  notify:
    - restart services
    - ensure custom logs directories exist

- name: Deploy watcher scripts includes
  copy:
    src: "{{ item }}"
    dest: "{{ watcher_scripts_includes }}"
  with_fileglob:
    - "templates/scripts/includes/*.sh"
  notify:
    - restart services
    - ensure custom logs directories exist

- name: Deploy watcher scripts templated includes
  template:
    src: "{{ item }}"
    dest: "{{ watcher_scripts_includes }}/{{ item | basename | regex_replace('.j2','') }}"
    mode: '0755'
  with_fileglob:
    - "templates/scripts/includes/*.j2"
  notify:
    - restart services
    - ensure custom logs directories exist

- name: Deploy simple scripts
  template:
    src: "{{ item }}"
    dest: "/usr/local/bin/{{ item | basename | regex_replace('.j2','') }}"
    mode: '0755'
  with_fileglob:
    - "templates/*.j2"
  notify:
    - restart services
    - ensure custom logs directories exist

- import_tasks: overrides.yml
- import_tasks: services.yml
