- name: Ensure scripts directory exists
  file:
    path: "/usr/local/bin/scripts/{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - ""
    - "includes"

- name: Copy scripts
  copy:
    src: "{{ item }}"
    dest: /usr/local/bin/scripts/
  with_fileglob:
    - "files/scripts/*.sh"
  notify: restart services

- name: Deploy watcher scripts
  template:
    src: "{{ item }}"
    dest: "/usr/local/bin/scripts/{{ item | basename | regex_replace('.j2','') }}"
    mode: '0755'
  with_fileglob:
    - "templates/scripts/*.j2"
  notify:
    - restart services
    - ensure wireguard logs directory exists
    - ensure geo ip cache directory exists

- name: Deploy watcher scripts includes
  copy:
    src: "{{ item }}"
    dest: /usr/local/bin/scripts/includes/
  with_fileglob:
    - "files/scripts/includes/*.sh"
  notify:
    - restart services
    - ensure wireguard logs directory exists
    - ensure geo ip cache directory exists

- name: Deploy watcher scripts templated includes
  template:
    src: "{{ item }}"
    dest: "/usr/local/bin/scripts/includes/{{ item | basename | regex_replace('.j2','') }}"
    mode: '0755'
  with_fileglob:
    - "templates/scripts/includes/*.j2"
  notify:
    - restart services
    - ensure wireguard logs directory exists
    - ensure geo ip cache directory exists

- name: Deploy simple scripts
  template:
    src: "{{ item }}"
    dest: "/usr/local/bin/{{ item | basename | regex_replace('.j2','') }}"
    mode: '0755'
  with_fileglob:
    - "templates/*.j2"
  notify:
    - restart services
    - ensure telegram bot log directory exists

- name: Deploy systemd services
  copy:
    src: "{{ item }}"
    dest: /etc/systemd/system/
  with_fileglob:
    - "files/systemd/*.service"
  notify: daemon reload

- name: Create systemd override directory for Docker
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: '0755'

- name: Add system shutdown notification depending on docker stop
  copy:
    dest: /etc/systemd/system/docker.service.d/system-shutdown-notification.conf
    content: |
      [Service]
      ExecStopPre=/usr/local/bin/telegram.sh "🔴 nuc-server shutting down with docker" status "$0"
  notify:
    - daemon reload

- name: Enable services
  systemd:
    name: "{{ item | basename | regex_replace('.service','') }}"
    enabled: yes
    state: started
  with_fileglob:
    - "files/systemd/*.service"
