- name: Create systemd override directories
  file:
    path: "{{ systemd_services }}/{{ item }}.service.d"
    state: directory
    mode: '0755'
  loop: "{{ service_override }}"

- name: Deploy systemd overrides
  template:
    src: templates/systemd/override.conf.j2
    dest: "{{ systemd_services }}/{{ item }}.service.d/service-telegram.conf"
  loop: "{{ service_override }}"
  notify:
    - reload overrided services
    - daemon reload
