- name: restart crowdsec
  service:
    name: crowdsec
    state: restarted

- name: reload crowdsec
  service:
    name: crowdsec
    state: reloaded

- name: restart nginx
  service:
    name: nginx
    state: restarted