prepend:
  - 5,PROCESS-NAME,YandexDisk4.exe,DIRECT
  - IP-CIDR,192.168.0.0/24,DIRECT
  - IP-CIDR,10.10.0.0/24,DIRECT
  - 2,PROCESS-NAME,:System,DIRECT
  - DOMAIN-REGEX,ryusandorosu.ru,DIRECT
  - DOMAIN-REGEX,gosuslugi.ru,DIRECT
  - DOMAIN-REGEX,tatenergosbyt.ru,DIRECT
  - DOMAIN,vk.com,DIRECT
  - DOMAIN-REGEX,vk-next.net,DIRECT
  - DOMAIN-REGEX,vknext.net,DIRECT
append: []
delete: [] 