mihomo_dashboard_link:
  uid: le_mihomo_dashboard
  panel_id:
    normal: 1
    relative: 2

mihomo_metrics:
  proxy_up_nodes:
    draw:
      ref: A
      name: up
      color: semi-dark-green
    query:
      match: "alive: true"
      type: range
      method: count
      mode: exact
    alert:
      title: Mihomo proxy is unavailable
      description: All proxy server nodes do not respond
      severity: error
      datasource: loki
    condition:
      operator: "=="
      value: 0
  proxy_down_nodes:
    draw:
      ref: B
      name: down
      color: dark-red
    query:
      match: "alive: false"
      type: range
      method: count
      mode: exact
    alert:
      title: Mihomo proxy health degradation
      description: Count of nodes which health checks have been failed
      severity: warning
      datasource: loki
    condition:
      operator: ">"
      value: 12
  proxy_healthcheck_latency:
    draw:
      ref: C
      name: ">1000ms"
      color: dark-yellow
    query:
      match: "delay: ([1-9][0-9]{3}|[1-9][0-9]{4,}) ms"
      type: range
      method: count
      mode: regex
    alert:
      title: Mihomo proxy increased latency
      description: Count of nodes having long duration of healthchecks (>1000ms)
      severity: warning
      datasource: loki
    condition:
      operator: ">"
      value: 10

mihomo_alerts:
  ref:
    reduce: D
    condition: E
  interval: 1m
  seek_period: 10m
  pending_period: 1m
