- name: Allow to run local scripts
  ansible.windows.win_powershell:
    script: Set-ExecutionPolicy RemoteSigned
  when: powershell_initial_setup

- name: Detect host profile
  set_fact:
    win_host_profile: >-
      {{
        whost
        | dict2items
        | selectattr('value.name', 'equalto', ansible_facts.env.COMPUTERNAME)
        | map(attribute='key')
        | first
      }}

- name: Add environment variables
  ansible.windows.win_powershell:
    script: |
      $PATH = [System.Environment]::GetEnvironmentVariables().PATH
      if ($PATH | Select-String -Pattern "{{ item }}" -SimpleMatch) {
        $Ansible.Changed = $false
      } else {
        [System.Environment]::SetEnvironmentVariable("PATH", "$PATH;{{ item }}", "User")
      }
  loop: "{{ winenvvars.custompaths[win_host_profile] }}"

- name: Install Starship
  win_chocolatey:
    name: starship
    state: present
