- name: Install sshfs
  apt:
    name: sshfs
    state: present

- name: Enable user_allow_other
  lineinfile:
    path: /etc/fuse.conf
    regexp: '^#?user_allow_other'
    line: 'user_allow_other'

- name: Ensure android mount dir exists
  file:
    path: "{{ android_mount_point }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0755'
