- name: Install Homebrew
  become: false
  shell: >
    NONINTERACTIVE=1 /bin/bash -c "$(
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
    )"

- name: Add Linuxbrew bin to root PATH
  copy:
    content: 'Defaults secure_path="{{ brew.bin }}:{{ brew.sbin }}:$DEFAULT_secure_path"'
    dest: /etc/sudoers.d/linuxbrew
    owner: root
    group: root
    mode: '0440'
    validate: '/usr/sbin/visudo -cf %s'
