vpn_watcher_labels:
  timestamp:
    bash: "{{ customlog_dateformat }}"
  ipsource:
    bash: ip
    label: true
  sourceport:
    bash: port
  device:
    bash: device_name
    label: true
  pubkey:
    bash: PUBKEY
    label: true
  ipdest:
    bash: vpn_ip
    label: true
  geoip:
    bash: (get_ip_geo $ip | jq)
    json: true

vpn_watcher_geoip_labels:
  country:
    json: geoip.country
  region:
    json: geoip.regionName
  city:
    json: geoip.city
  timezone:
    json: geoip.timezone
  asn:
    json: geoip.as
