- name: Create Apache Guacamole directories
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ guacamole_dir }}"
    - "{{ guacamole_dir }}/init"
    - "{{ guacamole_dir }}/pgdata"
    - "{{ guacamole_dir }}/extensions"

- name: Get latest guacamole version
  shell: >
    curl -s https://downloads.apache.org/guacamole/
    | grep -oP '<a href="(?P<version>\d+\.\d+\.\d+)/">'
    | tail -1 | grep -oP '[0-9\.]*'
  register: latest_guacamole_version

- name: Generate Guacamole PostgreSQL init script
  shell: >
    docker run --rm guacamole/guacamole:latest
    {{ guacamole_dir }}/bin/initdb.sh --postgresql
    > {{ guacamole_dir }}/init/initdb.sql
  args:
    creates: "{{ guacamole_dir }}/init/initdb.sql"

- name: Download TOTP extension
  get_url:
    url: "https://downloads.apache.org/guacamole/{{ latest_guacamole_version.stdout }}/binary/guacamole-auth-totp-{{ latest_guacamole_version.stdout }}.tar.gz"
    dest: "/tmp/guacamole-auth-totp-{{ latest_guacamole_version.stdout }}.tar.gz"

- name: Extract TOTP archive
  unarchive:
    src: "/tmp/guacamole-auth-totp-{{ latest_guacamole_version.stdout }}.tar.gz"
    dest: /tmp
    remote_src: yes

- name: Copy TOTP binary to extensions dir
  copy:
    src: "/tmp/guacamole-auth-totp-{{ latest_guacamole_version.stdout }}/guacamole-auth-totp-{{ latest_guacamole_version.stdout }}.jar"
    dest: "{{ guacamole_dir }}/extensions"
    remote_src: yes
    mode: '0755'

- name: Deploy docker-compose
  template:
    src: docker-compose.yml.j2
    dest: "{{ guacamole_dir }}/docker-compose.yml"

- name: Run containers
  community.docker.docker_compose_v2:
    project_src: "{{ guacamole_dir }}"
    state: present
    # recreate: always

- name: Wait for Guacamole to become available
  uri:
    url: "http://{{ localhost }}:{{ guacamole_port }}/guacamole/"
    status_code: 200
  register: result
  retries: 10
  delay: 5
  until: result.status == 200
