- name: Install Samba
  apt:
    name:
      - samba
      - smbclient
    state: present

- name: Deploy smb.conf
  template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
  notify: restart samba
