- name: Install Samba
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - samba
    - smbclient

- name: Deploy smb.conf
  template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
  notify: restart samba
