scripts_dir: /usr/local/bin/scripts

android_watcher_script: "{{ scripts_dir }}/android-watcher.sh"

# Notifications
telegram_script: /usr/local/bin/telegram.sh
watcher_scripts_includes: "{{ scripts_dir }}/includes"
ssh_watcher_script: "{{ scripts_dir }}/ssh-success-watcher.sh"
vpn_watcher_script: "{{ scripts_dir }}/vpn-success-watcher.sh"
f2b_tg_script: "{{ scripts_dir }}/f2b-notifications.sh"
docker_watcher_script: "{{ scripts_dir }}/docker-container-watcher.sh"
service_watcher_script: "{{ scripts_dir }}/service-state-watcher.sh"
