sshd_log: /var/log/auth.log
f2b_log: /var/log/fail2ban.log
wireguard_connections_log: /var/log/wireguard/{{ wireguard_interface }}_connections.log

geo_ip_cache: /var/cache/telegram/
telegram_bot_logs: /var/log/telegram
telegram_bot_error_log: "{{ telegram_bot_logs }}/message_error.log"
telegram_bot_success_log: "{{ telegram_bot_logs }}/message_success.log"

promtail_scrape_configs:
  - name: SSH authentication
    path: "{{ sshd_log }}"
  - name: Docker containers
    path: /var/lib/docker/containers/*/*.log
  - name: Wireguard connections
    path: "{{ wireguard_connections_log }}"
  - name: Telegram notifications
    path: "{{ telegram_bot_logs }}/*.log"
  - name: Fail2Ban
    path: "{{ f2b_log }}"
  - name: CrowdSec
    path: /var/log/crowdsec*.log
  - name: UFW
    path: /var/log/ufw.log
  - name: Samba
    path: /var/log/samba/log.*
  - name: Auditd
    path: /var/log/audit/audit.log
  - name: userlog
    path: /var/log/user.log
  - name: syslog
    path: /var/log/syslog

audit_paths:
  - /etc/ssh/sshd_config
  - /etc/systemd/system
  - /etc/group
  - /etc/shadow
  - /etc/sudoers
  - /etc/passwd
  - /etc/nftables.conf
  - /etc/wireguard/{{ wireguard_interface }}.conf
  - /etc/fail2ban/jail.local
  - /etc/msmtprc
  - /home/{{ user }}/.ssh/authorized_keys
