nft_log_prefix: "nft "

nftlog_prefix_labels:
  - chain
  - action

nftlog_labels:
  - SRC
  - DST
  - PROTO
  - SPT
  - DPT
  - MAC
  - MACSRC
  - MACDST
  - MACPROTO

nftlog_relabels:
  interface_in:
    regex: IN
    label: iif
  interface_out:
    regex: OUT
    label: oif
  exclude_source_ip:
    regex: SRC
    label: exclude_src
    default: "{{ home_ip }}"
