promtail_logs:
  status:
    name: Services and containers health
    path: "{{ telegram_bot_logs }}/systemd/*.log"
  kernel:
    name: System Kernel
    path: /var/log/kern.log
  wireguard:
    name: Wireguard connections
    path: "{{ custom_logs.wireguard }}"
  telegram:
    name: Telegram notifications
    path: "{{ telegram_bot_logs }}/*.log"
  ssh:
    name: SSH authentication
    path: "{{ sshd_log }}"
  fail2ban:
    name: Fail2Ban
    path: "{{ f2b_log }}"
  crowdsec:
    name: CrowdSec
    path: /var/log/crowdsec*.log
  user:
    name: userlog
    path: /var/log/user.log
  auditd:
    name: Auditd
    path: /var/log/audit/audit.log
  syslog:
    name: System
    path: /var/log/syslog
  nginx_access:
    name: Nginx sites access logs
    path: /var/log/nginx/*access.log
    pipeline: nginx
  nginx_error:
    name: Nginx errors
    path: /var/log/nginx/error.log

promtail_systemd:
  NetworkManager:
    name: Network Manager
  docker:
    name: Docker service
  android-watcher:
    name: Android SSHFS Auto Watcher
  nftables:
    name: nftables
  nginx:
    name: nginx
  ssh:
    name: SSH authentication
  systemd-logind:
    name: User login management
