promtail_logs:
  ssh:
    name: SSH authentication
    path: "{{ sshd_log }}"
  containers:
    name: Docker containers
    path: /var/lib/docker/containers/*/*.log
  status:
    name: Services and containers health
    path: "{{ telegram_bot_logs }}/systemd/*.log"
  wireguard:
    name: Wireguard connections
    path: "{{ custom_logs.wireguard }}"
  telegram:
    name: Telegram notifications
    path: "{{ telegram_bot_logs }}/*.log"
  fail2ban:
    name: Fail2Ban
    path: "{{ f2b_log }}"
  crowdsec:
    name: CrowdSec
    path: /var/log/crowdsec*.log
  auditd:
    name: Auditd
    path: /var/log/audit/audit.log
  user:
    name: userlog
    path: /var/log/user.log
  syslog:
    name: syslog
    path: /var/log/syslog
  nginx_access:
    name: Nginx sites access logs
    path: /var/log/nginx/*access.log
    pipeline: nginx
  nginx_error:
    name: Nginx errors
    path: /var/log/nginx/error.log

promtail_systemd:
  ssh:
    name: SSH authentication
  nftables:
    name: nftables
  proxy-healthcheck:
    name: Proxy healthcheck
  android-watcher:
    name: Android SSHFS Auto Watcher
