promtail_logs:
  edgerouter:
    name: EdgeRouter
    path: "{{ rsyslog.edgerouter }}"
  status:
    name: Services and containers health
    path: "{{ telegram_bot_logs }}/systemd/*.log"
  vpn-watcher:
    name: VPN connection success watcher
    path: "{{ custom_logs.wireguard.watcher }}"
  kernel:
    name: System Kernel
    path: "{{ system_logs.kernel }}"
  syslog:
    name: System
    path: /var/log/syslog
  ssh:
    name: SSH authentication
    path: "{{ system_logs.sshd }}"
  user:
    name: userlog
    path: /var/log/user.log
  auditd:
    name: Auditd
    path: "{{ system_logs.auditd }}"
    pipeline: auditd
  crowdsec:
    name: CrowdSec
    path: /var/log/crowdsec*.log
  wireguard:
    name: Wireguard connections
    path: "{{ custom_logs.wireguard.connect }}"
    pipeline: watcher_vpn
  telegram:
    name: Telegram notifications
    path: "{{ telegram_bot_logs }}/*log.json"
    pipeline: telegram
  nftables:
    name: nftables actions
    path: "{{ rsyslog.nftables }}"
    pipeline: nftables
  fail2ban_logs:
    name: Fail2Ban
    path: "{{ system_logs.fail2ban }}"
    pipeline: fail2ban_log
  nginx_access:
    name: Nginx sites access logs
    path: /var/log/nginx/*access.log
    pipeline: nginx_access
  nginx_error:
    name: Nginx errors
    path: /var/log/nginx/error.log
    pipeline: nginx_error
  fail2ban_actions:
    name: Fail2Ban Actions
    path: "{{ custom_logs.fail2ban }}"
    pipeline: fail2ban_action

promtail_systemd:
  - docker
  - android-watcher
  - NetworkManager
  - ssh
  - systemd-logind
  - wg-quick@{{ wireguard_interface }}
  - vpn-success-watcher
  - nginx
  - logrotate
