# Subnets
wireguard_network: 10.10.0.0/24
home_network: 192.168.0.0/24
docker_network: 172.16.0.0/12
docker_monitoring_network: 172.18.0.0/16

wireguard_server_ip: 10.10.0.1
wireguard_devices:
  large_laptop:
    ip: 10.10.0.2
    name: Asus K95VB
  phone:
    ip: 10.10.0.3
    name: Redmi 14C
  pad:
    ip: 10.10.0.4
    name: Samsung Galaxy Tab A6
  laptop:
    ip: 10.10.0.5
    name: Honor MagicBook X 14

# Home Network
home_ip: 87.117.169.26
lan_interface: wlp2s0
lan_ip:
  large_laptop: 192.168.0.101
  server: 192.168.0.107
  diskstation: 192.168.0.111
  icl_srv: 192.168.0.109

# not used
docker_monitoring_ip: 172.18.0.1
