localhost: 127.0.0.1

sshd_port: 22
dns_port: 53
dns_tls_port: 853
dhcp_request_port: 67
dhcp_resolve_port: 68
http_port: 80
https_port: 443
syslog_port: 514
smtp_port: 587
ssdp_port: 1900

#samba
smb_netbios_udp_ns_port: 137
smb_netbios_udp_dg_port: 138
smb_netbios_tcp_port: 139
smb_port: 445

#services_internal
internal_port:
  prometheus: 9090
  guacamole: 8080
