localhost: 127.0.0.1

sshd_port: 22
http_port: 80
https_port: 443
smtp_port: 587

#samba
smb_netbios_udp_ns_port: 137
smb_netbios_udp_dg_port: 138
smb_netbios_tcp_port: 139
smb_port: 445

#services_internal
const_prometheus_port: 9090
