docker:
  mihomo: mihomo
  promtail: promtail
  loki: loki
  grafana: grafana
  prometheus: prometheus
  node_exporter: node_exporter
  wireguard_exporter: wg_exporter
  wireguard_dashboard: wg_dashboard
  fail2ban_exporter: f2b_exporter
  cadvisor: cadvisor
  smartctl_exporter: smartctl_exporter
  snmp_exporter: snmp_exporter
  oauth2proxy: oauth2-proxy
  authelia: authelia
