docker:
  mihomo: mihomo
  nginx_auth: "{{ nginx_authentication }}"
  promtail: promtail
  loki: loki
  grafana: grafana
  prometheus: prometheus
  metric_exporters:
    node: node_exporter
    wireguard: wg_exporter
    fail2ban: f2b_exporter
    cadvisor: cadvisor
    smartctl: smartctl_exporter
    snmp: snmp_exporter
    blackbox: blackbox_exporter
  privoxy: privoxy
  wireguard_dashboard: wg_dashboard
  mihomo_dashboard: "{{ mihomo_web_interface }}"
