docker:
  mihomo: mihomo
  mihomo_dashboard: "{{ clash_web_interface }}"
  promtail: promtail
  loki: loki
  grafana: grafana
  prometheus: prometheus
  metric_exporters:
    node: node_exporter
    wireguard: wg_exporter
    fail2ban: f2b_exporter
    cadvisor: cadvisor
    smartctl: smartctl_exporter
    snmp: snmp_exporter
    blackbox: blackbox_exporter
    clash: clash_exporter
  wireguard_dashboard: wg_dashboard
  oauth2proxy: oauth2-proxy
  authelia: authelia
