bad_bot:
  - sqlmap
  - nikto
  - acunetix
  - dirbuster
  - gobuster
  - feroxbuster
  - masscan
  - nmap
  - zmap
  - zgrab
  - ffuf
  - dirsearch
  - wpscan
  - nvdorz
  - Scanner
  - DomainChecker
  - l9explore
  - Go-http-client
  - l9scan
  - leakix
  - Shodan-Pull

bad_bot_regex: "{{ bad_bot | join('|') }}"

tarpit:
  - \.php
  - \.env
  - \.git
  - \.sql
  - \.bak
  - \.old
  - \.aws
  - \.ssh
  - \.svn
  - \.kube
  - \.docker
  - \.htaccess
  - \.DS_Store
  - \.go
  - \.well-known/(?!acme-challenge)
  - wp-admin
  - wp-login
  - wp-config
  - wordpress
  - xmlrpc
  - phpmyadmin
  - phpunit
  - id_rsa
  - login
  - vendor
  - wget
  - curl
  - owa
  - ecp
  - jdni
  - evox
  - sdk
  - nmap
  - cgi-bin
  - dns-query
  - autodiscover
  - powershell
  - actuator
  - exchange
  - adminer
  - boaform
  - swagger
  - graphql
  - gql
  - telescope
  - webjars
  - microsoft.exchange
  - composer\.json
  - 'ldap://'
  - 'rmi://'
  - 'dns://'
  - HNAP1
  - MGLNDD
  - LEAKIX
  - ReportServer
  - developmentserver
  - metadatauploader
  - onvif
  - ssdpcgi
  - ignition

tarpit_regex: "{{ tarpit | join('|') }}"