domain: ryusandorosu.ru

mihomo_web_interface: metacubexd #yacd, metacubexd
nginx_authentication: oauth #oauth, authelia

nginx_public_sites:
  - "{{ domain }}"
  - "www.{{ domain }}"

nginx_allowed:
  - "{{ wireguard_network }}"
  - "{{ home_network }}"
  - "{{ home_ip }}"

nginx_private_sites:
  auth:
    authentication: false
    port: "{{ oauthproxy_port }}"
    proto: http
  cockpit:
    authentication: false
    port: "{{ cockpit_port }}"
    proto: https
  grafana:
    authentication: true
    port: "{{ grafana_port }}"
    proto: http
  prometheus:
    authentication: true
    port: "{{ prometheus_port }}"
    proto: http
  wg:
    authentication: false
    port: "{{ wireguard_dashboard_port }}"
    proto: http
  clash:
    authentication: true
    port: "{{ metacubexd_port }}"
    proto: http
  mihomo:
    authentication: false
    port: "{{ clash_web_port }}"
    proto: http
  guac:
    authentication: true
    bypass: false
    port: "{{ guacamole_port }}"
    proto: http
  actual:
    authentication: true
    port: "{{ actual_port }}"
    proto: http

letsencrypt_domains: >-
  {{
    nginx_public_sites
    +
    (
      nginx_private_sites.keys()
      | map('regex_replace', '^(.*)$', '\1.' ~ domain)
      | list
    )
  }}

nginx_hosts: >-
  {{
    dict(
      nginx_private_sites.keys()
      | zip(
          nginx_private_sites.keys()
          | map('regex_replace', '^(.*)$', 'https://\1.' ~ domain)
        )
    )
  }}
