user: ryusandorosu

sshd_allow_users:
  - "{{ user }}"

# SSHFS
termux:
  redmi:
    user: u0_a497
    key: android_termux
  samsung:
    user: u0_a145
    key: android_samsung
  x96q:
    user: u0_a87
    key: android_x96q
  # tronsmart:
  #   user: u0_axx
  #   key: android_tronsmart

# Windows
win_asus_user: Булат Сибгатуллин
win_honor_user: kutae

# services
grafana_user: 472
loki_user: 10001
prometheus_user: 65534

# Ubiquiti EdgeRouter Lite (ERLite-3)
ubnt_user: ubnt
router_ssh_key: "/home/{{ user }}/.ssh/router"
router_ssh_host: "{{ ubnt_user }}@{{ lan_ip.router }}"
