user: ryusandorosu
homedir: "/home/{{ user }}"

sshd_allow_users:
  - "{{ user }}"

# SSHFS
termux:
  redmi:
    user: u0_a497
    key: android_redmi
  samsung:
    user: u0_a145
    key: android_samsung
  x96q:
    user: u0_a87
    key: android_x96q

# Windows
### think how to define whost.*.name without whost.*.host
whost:
  asus:
    user: Булат Сибгатуллин
    name: DESKTOP-5EFI5KM
    host: local-asus
  honor:
    user: kutae
    name: DESKTOP-2MJ0UCN
    host: local-honor

# services
grafana_user: 472
loki_user: 10001
prometheus_user: 65534
