- name: Ensure .ssh dir
  file:
    path: "{{ ansible_facts.env.SUDO_HOME }}/.ssh"
    state: directory
    mode: '0700'
    owner: "{{ user }}"

- name: Validate SSH config
  assert:
    that:
      - item.value.hostname == item.key
    fail_msg: "GitHub host is different from its hostname"
  loop: "{{ ssh_hosts | dict2items }}"
  when: item.value.hostname == "github.com"

- name: Deploy SSH config
  template:
    src: config.j2
    dest: "{{ ansible_facts.env.SUDO_HOME }}/.ssh/config"
    mode: '0600'
    owner: "{{ user }}"

- name: Deploy SSH authorized keys
  template:
    src: authorized_keys.j2
    dest: "{{ ansible_facts.env.SUDO_HOME }}/.ssh/authorized_keys"
    mode: '0600'
    owner: "{{ user }}"
