- name: check proxy
  shell: curl --proxy socks5h://127.0.0.1:{{ socks5_port }} https://api.ipify.org
  register: proxy_check
  retries: 5
  delay: 5
  until: proxy_check.rc == 0

- name: check telegram availability
  shell: curl --proxy socks5h://127.0.0.1:{{ socks5_port }} https://api.telegram.org
  register: telegram_check
  retries: 5
  delay: 5
  until: telegram_check.rc == 0
