- name: Create config dir
  file:
    path: /etc/clash
    state: directory
    mode: '0755'

- name: Load dns variables
  include_vars: "{{ role_path }}/defaults/dns.yml"
- name: Load proxies variables
  include_vars: "{{ role_path }}/defaults/proxies.yml"
- name: Load subscription variables
  include_vars: "{{ role_path }}/defaults/subscription.yml"

- name: Deploy config
  template:
    src: config.yaml.j2
    dest: /etc/clash/config.yaml
  notify:
    - validate config in container
    - check proxy
    - check telegram availability

- name: Pull mihomo image
  community.docker.docker_image:
    name: metacubex/mihomo
    tag: latest
    source: pull

- name: Run mihomo container
  community.docker.docker_container:
    name: mihomo
    image: metacubex/mihomo:latest
    restart_policy: unless-stopped
    recreate: true
    restart: true
    ports:
      - "{{ clash_mixed_port }}:{{ clash_mixed_port }}"
      - "{{ socks5_port }}:{{ socks5_port }}"
    volumes:
      - /etc/clash:/root/.config/mihomo
