localhost: 127.0.0.1

const_port:
  sshd: 22
  dns: 53
  dns_tls: 853
  dhcp:
    request: 67
    resolve: 68
  http: 80
  https: 443
  syslog: 514
  smtp: 587
  ssdp: 1900
  smb:
    port: 445
    netbios:
      udp_ns: 137
      udp_dg: 138
      tcp: 139
