lan_interface: wlp2s0
home_ip: 87.117.169.26

# affected roles to deploy on change: firewall,fail2ban,nginx notifications:watchers windows:clashmeta
home_network: 192.168.0.0/23 # includes 192.168.0.0/24 and 192.168.1.0/24
# lan_networks:
#   - 192.168.0.0/24
#   - 192.168.1.0/24

# affected roles to deploy on change: mounts,samba,sshcli,grafana ; not necessary to deploy but affects: if running any windows playbook
lan_ip:
  router: 192.168.0.1
  wifi: 192.168.0.2
  server: 192.168.0.100
  large_laptop: "{{ asus_lan.wired_to_tplink }}"
  small_laptop: 192.168.0.102
  diskstation: 192.168.0.111
  icl_srv: 192.168.0.109
  x96q: 192.168.0.96
  tronsmart: 192.168.0.113

asus_lan:
  wireless_tplink: 192.168.0.101      # eth1 a8:29:48:87:f5:70
  wired_to_tplink: 192.168.0.103      # eth1 74:d0:2b:62:81:0c
  wired_to_router: 192.168.1.100      # eth2 a8:29:48:87:f5:70
  wireless_audiocodes: 192.168.1.100  # eth2 a8:29:48:87:f5:70
