domain: ryusandorosu.ru

mihomo_interface:
  name: metacubexd
  port: 9094
  changelog: https://github.com/MetaCubeX/metacubexd/releases
  version: cat .output/server/package.json | jq -r .version
nginx_authentication:
  name: oauth
  port: 4180
  changelog: https://github.com/oauth2-proxy/oauth2-proxy/releases
  # name: authelia
  # port: 9095 #9091
  # changelog: https://github.com/authelia/authelia/releases

nginx_public_sites:
  - "{{ domain }}"
  - "www.{{ domain }}"

nginx_allowed:
  - "{{ wireguard_network }}"
  - "{{ home_network }}"
  - "{{ home_ip }}"

nginx_private_sites:
  auth:
    authentication: false
    port: "{{ docker.nginx_auth.port }}"
    proto: http
  cockpit:
    authentication: false
    port: "{{ local_port.cockpit }}"
    proto: https
  grafana:
    authentication: true
    port: "{{ docker.grafana.port }}"
    proto: http
  prometheus:
    authentication: true
    port: "{{ docker.prometheus.port.exposed }}"
    proto: http
  wg:
    authentication: false
    port: "{{ docker.wireguard_dashboard.port }}"
    proto: http
  clash:
    authentication: true
    port: "{{ docker.mihomo_dashboard.port }}"
    proto: http
  mihomo:
    authentication: false
    port: "{{ docker.mihomo.port.web }}"
    proto: http
  guac:
    authentication: true
    bypass: true
    port: "{{ docker.guacamole.port.exposed }}"
    proto: http
  actual:
    authentication: true
    port: "{{ docker.actual.port }}"
    proto: http

letsencrypt_domains: >-
  {{
    nginx_public_sites
    +
    (
      nginx_private_sites.keys()
      | map('regex_replace', '^(.*)$', '\1.' ~ domain)
      | list
    )
  }}

nginx_hosts: >-
  {{
    dict(
      nginx_private_sites.keys()
      | zip(
          nginx_private_sites.keys()
          | map('regex_replace', '^(.*)$', 'https://\1.' ~ domain)
        )
    )
  }}
