local_port:
  wireguard: 51820
  cockpit: 9090
  wifi_ap: 8082
  appsec: 7422

lan_port:
  synology_dsm: 5001
  termux: 8022

# affected roles to deploy on change: nginx,grafana,promtail,prometheus notifications:services
docker:
  mihomo:
    name: mihomo
    port:
      mixed: 7890 #http and socks5
      socks5: 7891
      web: 9092
    changelog: https://github.com/MetaCubeX/mihomo/releases

  mihomo_dashboard:
    name: "{{ mihomo_interface.name }}"
    port: "{{ mihomo_interface.port }}"
    changelog: "{{ mihomo_interface.changelog }}"
    version: "{{ mihomo_interface.version }}"
  wireguard_dashboard:
    name: wg_dashboard
    port: 10086

  nginx_auth:
    name: "{{ nginx_authentication.name }}"
    port: "{{ nginx_authentication.port }}"
    changelog: "{{ nginx_authentication.changelog }}"

  # monitoring
  promtail:
    name: promtail
    port: 9080
  loki:
    name: loki
    port: 3100
    changelog: https://github.com/grafana/loki/blob/main/CHANGELOG.md
  grafana:
    name: grafana
    port: 3000
    changelog: https://github.com/grafana/grafana/blob/main/CHANGELOG.md
  privoxy:
    name: privoxy
    port: 8118 #http_proxy_port
  prometheus:
    name: prometheus
    port:
      exposed: 9091
      internal: 9090
    changelog: https://github.com/prometheus/prometheus/blob/main/CHANGELOG.md

  monitoring:
    node:
      name: node_exporter
      port: 9100
    wireguard:
      name: wg_exporter
      port: 9586
    fail2ban:
      name: f2b_exporter
      port: 9191
    cadvisor:
      name: cadvisor
      port: 8080
    smartctl:
      name: smartctl_exporter
      port: 9633
    snmp:
      name: snmp_exporter
      port: 9116
    blackbox:
      name: blackbox_exporter
      port: 9115
    nginx:
      name: nginx_exporter
      port: 9113

  # guacamole network
  guacd:
    name: guacd
  postgres:
    name: postgres
  guacamole:
    name: guacamole
    port:
      exposed: 8085
      internal: 8080
    changelog: https://guacamole.apache.org/releases/

  ### non-infra:
  actual:
    name: actual
    port: 5006
    changelog: https://actualbudget.org/docs/releases/
    version: "cat package.json | jq -r .version"
  vdf:
    name: vdf
    port:
      exposed: 8888
      internal: 8080

### docker dictionary ends here ###
