firewall_tcp_ports:
  - "{{ sshd_port }}"
  - "{{ http_port }}"
  - "{{ https_port }}"

firewall_udp_ports:
  - "{{ wireguard_port }}"

lan_interface: wlp2s0
lan_ports:
  - "{{ smb_netbios_port }}"
  - "{{ smb_port }}"
  - "{{ cockpit_port }}"
