firewall_tcp_ports:
  - "{{ sshd_port }}"
  - "{{ http_port }}"
  - "{{ https_port }}"

firewall_udp_ports:
  - "{{ wireguard_port }}"

firewall_lan_tcp_ports:
  - "{{ smb_netbios_tcp_port }}"
  - "{{ smb_port }}"
  - "{{ cockpit_port }}"
  - "{{ synology_dsm_port }}"

firewall_lan_udp_ports:
  - "{{ smb_netbios_udp_ns_port }}"
  - "{{ smb_netbios_udp_dg_port }}"

monitoring_exporter_ports:
  - "{{ wireguard_exporter_port }}"
  - "{{ snmp_exporter_port }}"
