- import_tasks: server.yml
  when: ansible_facts.hostname == "nuc-server"

- name: Install Homebrew
  become: false
  shell: >
    NONINTERACTIVE=1 /bin/bash -c "$(
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
    )"

- name: Install essential packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - git # omz needs it
    - curl
    - jq # watcher scripts need to run it as root
    - tcpdump
    - gcc
    - make
    - ca-certificates
    - build-essential

- name: Install additional packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - tree
    - rsync
    - unattended-upgrades
    - bind9-dnsutils
    - btop
    - strace
    - bubblewrap
    - autossh
    - plocate
    - lnav

- name: Install newer packages from Homebrew
  become: false
  community.general.homebrew:
    name: "{{ item }}"
    state: present
    update_homebrew: true
  loop:
    - bat
    - jq
    - yq
    - sad
    - sd
  # nvim requirements also used in zsh fzf plugin:
    - fd
    - ripgrep

- import_tasks: configs.yml

- name: Install required Ansible collections
  become: false
  command: ansible-galaxy collection install {{ item }} --upgrade
  loop:
    - community.docker
    - ansible.windows
    - chocolatey.chocolatey
