- import_tasks: server.yml
  when: ansible_facts.hostname == "nuc-server"

- name: Install base packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - git
    - curl
    - jq
    - tree
    - bat
    - tcpdump
    - rsync
    - gcc
    - make
    - ca-certificates
    - unattended-upgrades
    - build-essential
    - bind9-dnsutils
    - btop
    - strace
    - bubblewrap
    - autossh
    - plocate

- name: Ensure bat config directory exists
  file:
    path: "{{ item }}/.config/bat/"
    state: directory
  loop:
    - "{{ homedir }}"
    - "{{ ansible_facts.env.HOME }}"

- name: Bat settings
  copy:
    content: |
      --color=always
      --style=plain
      --paging=never
    dest: "{{ item }}/.config/bat/config"
  loop:
    - "{{ homedir }}"
    - "{{ ansible_facts.env.HOME }}"

- name: Print motd to check updates
  copy:
    src: update-motd.d/updates.sh
    dest: /etc/update-motd.d/93-updates
    mode: '0755'

- name: Enable apt unattended-upgrades
  copy:
    src: apt.conf.d/auto-upgrades
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    mode: '0644'

- name: Install required Ansible collections
  become: false
  command: ansible-galaxy collection install {{ item }} --upgrade
  loop:
    - community.docker
    - ansible.windows
    - chocolatey.chocolatey
