- import_tasks: server.yml
  when: ansible_facts.hostname == "nuc-server"

- name: Install base packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - git # omz needs it
    - curl
    - jq
    - tree
    - tcpdump
    - rsync
    - gcc
    - make
    - ca-certificates
    - unattended-upgrades
    - build-essential
    - bind9-dnsutils
    - btop
    - strace
    - bubblewrap
    - autossh
    - plocate

- name: Install newer packages from Homebrew
  become: false
  community.general.homebrew:
    name: "{{ item }}"
    state: present
    update_homebrew: true
  loop:
    - bat
    - yq
    - sad
    - sd
  # nvim requirements also used in zsh fzf plugin:
    - fd
    - ripgrep

- import_tasks: rc.yml

- name: Enable apt unattended-upgrades
  copy:
    src: apt.conf.d/auto-upgrades
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    mode: '0644'

- name: Install required Ansible collections
  become: false
  command: ansible-galaxy collection install {{ item }} --upgrade
  loop:
    - community.docker
    - ansible.windows
    - chocolatey.chocolatey
