- name: Ensure bat config directory exists
  file:
    path: "{{ item }}/.config/bat/"
    state: directory
  loop:
    - "{{ homedir }}"
    - "{{ ansible_facts.env.HOME }}"

- name: Bat settings
  copy:
    content: |
      --color=always
      --style=plain
      --paging=never
    dest: "{{ item }}/.config/bat/config"
  loop:
    - "{{ homedir }}"
    - "{{ ansible_facts.env.HOME }}"
