- name: Load all defaults recursively
  include_vars:
    dir: "{{ role_path }}/defaults"
    extensions: ["yml"]
  tags: [vars]

- name: Locate updatedb settings
  template:
    src: plocatedb.conf.j2
    dest: /etc/updatedb.conf
    mode: '0644'
  notify: update db

- name: Install elio from Homebrew
  become: false
  community.general.homebrew:
    name: elio
    state: present
    update_homebrew: true

- name: Remove mail from motd
  file:
    path: "/var/mail/{{ user }}"
    state: absent
