- name: Load values
  include_vars: "{{ item }}"
  with_fileglob:
    - defaults/*.yml
    - "{{ role_path }}/../promtail/defaults/labels/nftables.yml"
  tags: [vars]

- debug:
    msg: "dict={{ const_port.sshd }} ({{ const_port.sshd | type_debug }}), var={{ sshd_port }} ({{ sshd_port | type_debug }})"
- debug:
    msg: "{{ item }} -> {{ item | type_debug }}"
  loop: "{{ firewall_tcp_ports }}"
- debug:
    msg: "in-check: {{ const_port.sshd in firewall_tcp_ports }}"

- name: Ensure required network vars defined
  assert:
    that:
      - wireguard_interface is defined
      - wireguard_network is defined
      - local_port.wireguard is defined
    fail_msg: "Required WireGuard variables are not defined"

### this task makes sense if it is not rejected from the rule allowing tcp ports to separately set allowing only via wireguard interface
- name: Ensure SSH port is allowed in firewall
  assert:
    that: const_port.sshd in (firewall_tcp_ports | map('int') | list)
    fail_msg: "SSH port is not listed in firewall settings"

- name: Install nftables
  apt:
    name: nftables
    state: present

- name: Create systemd override directory
  file:
    path: "{{ systemd_services }}/nftables.service.d"
    state: directory
    mode: '0755'

- name: Get wireguard service status
  systemd:
    name: wg-quick@{{ wireguard_interface }}
  register: wg_service
  failed_when: false
  changed_when: false

- name: Fail if wireguard service is not enabled
  fail:
    msg: "WireGuard service wg-quick@{{ wireguard_interface }} is not enabled"
  when: wg_service.status.UnitFileState != "enabled"

- name: Deploy nftables override
  template:
    src: override.conf.j2
    dest: "{{ systemd_services }}/nftables.service.d/override.conf"
  notify: daemon reload

- name: Deploy nftables config
  template:
    src: nftables.conf.j2
    dest: /etc/nftables.conf
  notify: reload nftables

- name: Enable and start nftables
  systemd:
    name: nftables
    enabled: yes
    state: started
