- name: Install zsh and its plugin dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - zsh
    - bc
    - command-not-found
    - silversearcher-ag
    - fasd

# https://github.com/sharkdp/fd - fd-find is too old for ubuntu, not so fresh for debian to install from apt. the package is already present in neovim role, but for direct usage brew version is preferred
# https://github.com/clvv/fasd
# https://github.com/junegunn/fzf
# https://github.com/BurntSushi/ripgrep
- name: Install productivity utils and plugin dependencies from Homebrew
  become: false
  homebrew:
    name: fzf
    state: present
    update_homebrew: true
  loop:
    - fzf
    - fd
    # - ripgrep

# - name: Clone oh-my-zsh
#   become_user: "{{ user }}"
#   git:
#     repo: https://github.com/ohmyzsh/ohmyzsh.git
#     dest: "{{ homedir }}/{{ omz }}"
#     version: master
#     update: no

# - name: Make zsh default shell for root
#   become_user: root
#   shell: "chsh -s $(which zsh)"

# - name: Clone zsh plugins
#   become_user: "{{ user }}"
#   git:
#     repo: "{{ item }}"
#     dest: "{{ homedir }}/{{ omz_plug_dir }}/{{ item | basename }}"
#   loop:
#     - https://github.com/zsh-users/zsh-syntax-highlighting
#     - https://github.com/zsh-users/zsh-autosuggestions

- name: Symlink omz for root
  file:
    src: "{{ homedir }}/{{ omz }}"
    dest: "{{ ansible_facts.env.HOME }}/{{ omz }}"
    state: link

- name: Clone personal configs repo
  become_user: "{{ user }}"
  git:
    repo: "{{ zsh_repo_url }}"
    dest: "{{ homedir }}/{{ zsh_repo_dir }}"

- name: Symlink configs repo for root
  file:
    src: "{{ homedir }}/{{ zsh_repo_dir }}"
    dest: "{{ ansible_facts.env.HOME }}/{{ zsh_repo_dir }}"
    state: link

- name: Symlink .zshrc
  become_user: "{{ item | basename }}"
  file:
    src: "{{ item }}/{{ zsh_repo_dir }}/.zshrc"
    dest: "{{ item }}/.zshrc"
    state: link
  loop:
    - "{{ homedir }}"
    - "{{ ansible_facts.env.HOME }}"

- name: Symlink custom theme - passion
  become_user: "{{ item | basename }}"
  file:
    src: "{{ homedir }}/{{ zsh_repo_dir }}/passion.zsh-theme"
    dest: "{{ item }}/{{ omz_themes }}/passion.zsh-theme"
    state: link
  loop:
    # - "{{ homedir }}"
    - "{{ ansible_facts.env.HOME }}"

- name: Enable command-not-found for zsh
  command: update-command-not-found
