- set_fact:
    zsh_repo_url: git@github.com:ryusandorosu/zsh-improved.git
- set_fact:
    zsh_repo_dir: "{{ zsh_repo_url | basename | regex_replace('.git','') }}"

- name: Install zsh
  apt:
    name: zsh
    state: present
    update_cache: yes

# {{ zsh_repo_url }}/init.sh does the same
- name: Clone personal configs repo
  become_user: "{{ user }}"
  git:
    repo: "{{ zsh_repo_url }}"
    dest: "{{ homedir }}/{{ zsh_repo_dir }}"

# {{ zsh_repo_url }}/init.sh does the same. but ansible behaves correctly on creating symlink for root so it is preferred
- name: Symlink .zshrc
  become_user: "{{ item | basename }}"
  file:
    src: "{{ item }}/{{ zsh_repo_dir }}/.zshrc"
    dest: "{{ item }}/.zshrc"
    state: link
  loop:
    - "{{ homedir }}"
    - "{{ ansible_facts.env.HOME }}"
