tarpit:
  - \.php
  - \.env
  - \.git
  - \.sql
  - \.bak
  - \.old
  - \.aws
  - \.ssh
  - \.svn
  - \.kube
  - \.docker
  - \.htaccess
  - \.DS_Store
  - \.go
  - \.well-known/(?!acme-challenge)
  - wp-admin
  - wp-login
  - wp-config
  - wordpress
  - xmlrpc
  - phpmyadmin
  - phpunit
  - id_rsa
  - login
  - vendor
  - wget
  - curl
  - owa
  - ecp
  - jdni
  - evox
  - sdk
  - nmap
  - cgi-bin
  - dns-query
  - autodiscover
  - powershell
  - actuator
  - exchange
  - adminer
  - boaform
  - swagger
  - graphql
  - gql
  - telescope
  - webjars
  - microsoft.exchange
  - composer\.json
  - 'ldap://'
  - 'rmi://'
  - 'dns://'
  - HNAP1
  - MGLNDD
  - LEAKIX
  - ReportServer
  - developmentserver
  - metadatauploader
  - onvif
  - ssdpcgi
  - ignition
  - sitemap
  - blog
  - kontakty
  - contact
  - about
  - txets
