- name: Create project directory
  file:
    path: "{{ oauth_compose }}"
    state: directory
    mode: "0755"

- name: Deploy config
  template:
    src: oauth/oauth2-proxy.cfg.j2
    dest: "{{ oauth_config }}"

- name: Deploy docker-compose
  template:
    src: oauth/docker-compose.yml.j2
    dest: "{{ oauth_compose }}/docker-compose.yml"

- name: Run oauth2-proxy container
  community.docker.docker_compose_v2:
    project_src: "{{ oauth_compose }}"
    state: present
    recreate: always

- name: Check oauth2-proxy container running status
  uri:
    url: "http://{{ localhost }}:{{ oauthproxy_port }}/ping"
    status_code: 200
  register: result
  retries: 5
  delay: 3
  until: result.status == 200
