- set_fact:
    initial_nvim_install: false
  tags: [vars]

- name: Load variables
  include_vars: "{{ item }}"
  with_fileglob:
    - defaults/*.yml
  tags: [vars]

- name: Install neovim AppImage from git repo
  get_url:
    url: https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.appimage
    dest: "{{ neovim }}"
    mode: '0777'

- name: Create config directories
  file:
    path: "{{ homedir }}/{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0775'
  loop:
    - "{{ nvimdir.config }}/lua/config"
    - "{{ nvimdir.config }}/lua/plugins"

- name: Ensure required root directories exist
  file:
    path: "{{ ansible_facts.env.HOME }}/{{ item }}"
    state: directory
  loop:
    - "{{ nvimdir.share | dirname }}"

- name: Deploy init.lua
  copy:
    src: files/init.lua
    dest: "{{ homedir }}/{{ nvimdir.config }}"
    mode: '0664'

- name: Deploy plugins.lua
  copy:
    src: files/lua/plugins.lua
    dest: "{{ homedir }}/{{ nvimdir.config }}/lua"
    mode: '0664'

- name: Deploy plugin configurations
  copy:
    src: "{{ item }}"
    dest: "{{ homedir }}/{{ nvimdir.config }}/lua/plugins"
    mode: '0664'
  with_fileglob:
    - "files/lua/plugins/*.lua"

- name: Deploy templated plugin configurations
  template:
    src: "{{ item }}"
    dest: "{{ homedir }}/{{ nvimdir.config }}/lua/plugins/{{ item | basename | regex_replace('.j2','') }}"
    mode: '0664'
  with_fileglob:
    - "templates/lua/plugins/*.lua.j2"

- name: Deploy lua configs
  copy:
    src: "{{ item }}"
    dest: "{{ homedir }}/{{ nvimdir.config }}/lua/config"
    mode: '0664'
  with_fileglob:
    - "files/lua/config/*.lua"

- name: Deploy templated lua configs
  template:
    src: "{{ item }}"
    dest: "{{ homedir }}/{{ nvimdir.config }}/lua/config/{{ item | basename | regex_replace('.j2','') }}"
    mode: '0664'
  with_fileglob:
    - "templates/lua/config/*.lua.j2"

- import_tasks: managers.yml
  when: initial_nvim_install

- name: Create root symlink for nvim configs
  file:
    src: "{{ homedir }}/{{ nvimdir.config }}"
    dest: "{{ ansible_facts.env.HOME }}/{{ nvimdir.config }}"
    state: link

- name: Create root symlink for nvim shares
  file:
    src: "{{ homedir }}/{{ nvimdir.share }}"
    dest: "{{ ansible_facts.env.HOME }}/{{ nvimdir.share }}"
    state: link

### seems useless
# - name: Set nvim as default sudoeditor
#   become_user: root
#   command: update-alternatives --install /usr/bin/sudoedit sudoedit {{ neovim }} 50
