- set_fact:
    initial_nvim_install: false
  tags: [vars]

- name: Load variables
  include_vars: "{{ item }}"
  with_fileglob:
    - defaults/*.yml
  tags: [vars]

- name: Install neovim AppImage from git repo
  get_url:
    url: https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.appimage
    dest: "{{ neovim }}"
    mode: '0777'

- name: Ensure directory structure exists
  file:
    path: "{{ homedir }}/{{ nvimdir.config }}/{{ item.path }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "{{ item.mode }}"
  with_community.general.filetree: files/
  when: item.state == 'directory'

- name: Ensure required root directories exist
  file:
    path: "{{ ansible_facts.env.HOME }}/{{ item }}"
    state: directory
  loop:
    - "{{ nvimdir.share | dirname }}"

- name: Deploy static files
  copy:
    src: "{{ item.src }}"
    dest: "{{ homedir }}/{{ nvimdir.config }}/{{ item.path }}"
    mode: "{{ item.mode }}"
  with_community.general.filetree: files/
  when: item.state == 'file'

- name: Deploy templated files
  template:
    src: "{{ item.src }}"
    dest: "{{ homedir }}/{{ nvimdir.config }}/{{ item.path | regex_replace('.j2', '') }}"
    mode: "{{ item.mode }}"
  with_community.general.filetree: templates/
  when: item.state == 'file'

- import_tasks: managers.yml
  when: initial_nvim_install

- name: Create root symlinks for nvim directories
  file:
    src: "{{ homedir }}/{{ item }}"
    dest: "{{ ansible_facts.env.HOME }}/{{ item }}"
    state: link
  loop:
    - "{{ nvimdir.share }}"
    - "{{ nvimdir.config }}"

### seems useless
# - name: Set nvim as default sudoeditor
#   become_user: root
#   command: update-alternatives --install /usr/bin/sudoedit sudoedit {{ neovim }} 50
