- name: Install CIFS
  apt:
    name: cifs-utils
    state: present

- name: Ensure mount directories exist
  file:
    path: "{{ item.value.mount }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0755'
  loop: >-
    {{
      shares
      | dict2items
      | rejectattr('key', 'equalto', 'shared')
      | list
    }}

- name: Mount NFS shares
  mount:
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: nfs
    opts: "{{ mount_opts | join(',') }}"
    state: present
  loop: "{{ nfs_mounts }}"

- name: Deploy Samba credential secrets for CIFS shares connections
  template:
    src: smb_credentials.j2
    dest: "{{ item.value.cifs.credentials.path }}"
    mode: '0600'
  loop: >-
    {{
      shares
      | dict2items
      | selectattr('value.cifs', 'defined')
      | list
    }}

- name: Mount CIFS shares
  mount:
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: cifs
    opts: "{{ item.opts | join(',') }},{{ mount_opts | join(',') }}"
    state: present
  loop: "{{ cifs_mounts }}"
