ssh_hosts:
  github.com:
    hostname: github.com
    user: git
    identity: github

  redmi:
    hostname: "{{ wireguard_devices.phone.ip }}"
    port: "{{ termux_port }}"
    user: "{{ termux.redmi.user }}"
    identity: "{{ termux.redmi.key }}"

  ds209:
    hostname: "{{ lan_ip.diskstation }}"
    user: admin
    identity: ds209
    options:
      - PubkeyAcceptedAlgorithms +ssh-rsa
      - HostKeyAlgorithms +ssh-rsa

  icl:
    hostname: "{{ lan_ip.icl_srv }}"
    user: "{{ user }}"
    identity: icl_srv

  router:
    hostname: "{{ lan_ip.router }}"
    user: ubnt
    identity: router

  samsung:
    hostname: "{{ wireguard_devices.pad.ip }}"
    port: "{{ termux_port }}"
    user: "{{ termux.samsung.user }}"
    identity: "{{ termux.samsung.key }}"
    path: /storage/0123-4567/

  smarttv:
    hostname: "{{ wireguard_devices.x96q.ip }}" #"{{ lan_ip.x96q }}"
    port: "{{ termux_port }}"
    user: "{{ termux.x96q.user }}"
    identity: "{{ termux.x96q.key }}"
  # smarttv:
  #   hostname: "{{ lan_ip.tronsmart }}"
  #   port: "{{ termux_port }}"
  #   user: "{{ termux.tronsmart.user }}"
  #   identity: "{{ termux.tronsmart.key }}"
