ssh_hosts:
  github.com:
    hostname: github.com
    user: git
    identity: github

  redmi:
    hostname: "{{ wireguard_devices.phone.ip }}"
    port: "{{ termux_port }}"
    user: "{{ termux.redmi.user }}"
    identity: "{{ termux.redmi.key }}"

  ds209:
    hostname: "{{ lan_ip.diskstation }}"
    user: admin
    identity: ds209
    options:
      - PubkeyAcceptedAlgorithms +ssh-rsa
      - HostKeyAlgorithms +ssh-rsa

  icl:
    hostname: "{{ lan_ip.icl_srv }}"
    user: "{{ user }}"
    identity: icl_srv

  router:
    hostname: "{{ lan_ip.router }}"
    user: ubnt
    identity: router

  samsung:
    hostname: "{{ wireguard_devices.pad.ip }}"
    port: "{{ termux_port }}"
    user: "{{ termux.samsung.user }}"
    identity: "{{ termux.samsung.key }}"

  smarttv:
    hostname: "{{ lan_ip.smarttv }}" #"{{ wireguard_devices.smarttv.ip }}"
    port: "{{ termux_port }}"
    user: "{{ termux.smarttv.user }}"
    identity: "{{ termux.smarttv.key }}"
