### note that all of these have instable graphic rendering
- set_fact:
    kmscon_vt: tty2

- name: Add trixie-backports repository
  deb822_repository:
    name: trixie-backports
    types: deb
    uris: http://deb.debian.org/debian
    suites: trixie-backports
    components:
      - main
      - contrib
      - non-free
      - non-free-firmware
    state: present

- name: Install kmscon from backports
  apt:
    name: kmscon
    state: present
    default_release: trixie-backports
    update_cache: yes

- name: Deploy kmscon.conf
  copy:
    src: kmscon.conf
    dest: /etc/kmscon/kmscon.conf
    mode: '0644'
  notify: restart kmscon

- name: Disable getty on target vt
  systemd:
    name: "getty@{{ kmscon_vt }}.service"
    enabled: false
    state: stopped

- name: Enable kmscon on target vt
  systemd:
    name: "kmsconvt@{{ kmscon_vt }}.service"
    enabled: true
    state: started

- name: Install Nerd Font's JetBrains Mono
  become: false
  community.general.homebrew:
    name: font-jetbrains-mono-nerd-font
    state: present

- name: Refresh font cache
  command: fc-cache -f

### in case if autovt gets pointing to ksmconvt on all ttys
## checks
# ls -la /etc/systemd/system/autovt@.service 2>/dev/null
# systemctl status getty@tty1.service getty@tty3.service getty@tty4.service getty@tty5.service getty@tty6.service
# loginctl list-sessions
## solution
# sudo rm /etc/systemd/system/autovt@.service && sudo systemctl daemon-reload
# sudo systemctl enable --now getty@tty1.service getty@tty3.service getty@tty4.service getty@tty5.service getty@tty6.service

### better consider using these
# 1) sudo apt install cage foot
# 2) sudo apt install xorg alacritty xinit
