- name: Install Nerd Font's JetBrains Mono
  become: false
  community.general.homebrew:
    name: font-jetbrains-mono-nerd-font
    state: present

- name: Refresh font cache
  command: fc-cache -f

- import_tasks: kmscon.yml
- import_tasks: wayland.yml
