shares:
  shared:
    mount: /srv/share
    samba:
      name: NUC

  redmi:
    mount: /mnt/redmi
    samba:
      name: REDMI

  samsung:
    mount: /mnt/samsung
    samba:
      name: SAMSUNG

  smarttv:
    mount: /mnt/x96q
    samba:
      name: SMARTTV

  diskstation:
    mount: /mnt/ds209
    nfs:
      pub:
        src: "{{ lan_ip.diskstation }}:/volume1/PUB"
      # web:
      #   src: "{{ lan_ip.diskstation }}:/volume1/web"
    samba:
      name: DS209

  win_asus:
    mount: /mnt/k95vb
    cifs:
      src: "//{{ lan_ip.large_laptop.wired }}/d"
      credentials:
        path: "{{ cifs_creds }}/asus"
        user: "{{ whost.asus.user }}"
        pass: "{{ vault_windows_asus_password }}"
    samba:
      name: K95VB

nfs_mounts: >-
  {{ lookup('template', inventory_dir ~ '/group_vars/all/templates/nfs.j2') | from_yaml }}

cifs_mounts: >-
  {{ lookup('template', inventory_dir ~ '/group_vars/all/templates/cifs.j2') | from_yaml }}

cifs_creds: /root/.smb
