prometheus_scrape_configs:
  node:
    target_src: "{{ docker.monitoring.node.name }}"
    target_port: "{{ docker.monitoring.node.port }}"
    labels: instance
  wireguard:
    target_src: "{{ lan_ip.server }}"
    target_port: "{{ docker.monitoring.wireguard.port }}"
  fail2ban:
    target_src: "{{ docker.monitoring.fail2ban.name }}"
    target_port: "{{ docker.monitoring.fail2ban.port }}"
    labels: instance
  cadvisor:
    target_src: "{{ docker.monitoring.cadvisor.name }}"
    target_port: "{{ docker.monitoring.cadvisor.port }}"
    labels: instance
  smartctl:
    target_src: "{{ docker.monitoring.smartctl.name }}"
    target_port: "{{ docker.monitoring.smartctl.port }}"
    labels: instance
  nginx:
    target_src: "{{ lan_ip.server }}"
    target_port: "{{ docker.monitoring.nginx.port }}"
    labels: instance

prometheus_scrape_configs_extended:
  snmp_diskstation:
    path: /snmp
    replacement:
      src: "{{ lan_ip.server }}"
      port: "{{ docker.monitoring.snmp.port }}"
    params:
      module: synology
      auth: public_v2
    targets:
      - "{{ lan_ip.diskstation }}"
  snmp_edgerouter:
    path: /snmp
    replacement:
      src: "{{ lan_ip.server }}"
      port: "{{ docker.monitoring.snmp.port }}"
    params:
      module:
        - system
        - if_mib
      auth: public_v2
    targets:
      - "{{ lan_ip.router }}"
  blackbox:
    path: /probe
    replacement:
      src: "{{ docker.monitoring.blackbox.name }}"
      port: "{{ docker.monitoring.blackbox.port }}"
    params:
      module: http_2xx
    targets:
      - https://api.telegram.org
      - https://www.gstatic.com/generate_204
      - https://github.com
  blackbox_edgerouter:
    path: /probe
    replacement:
      src: "{{ docker.monitoring.blackbox.name }}"
      port: "{{ docker.monitoring.blackbox.port }}"
    params:
      module: http_2xx_insecure
    targets:
      - "https://{{ lan_ip.router }}"
