logrotate_configs:
  tg-error:
    path: "{{ custom_logs.telegram.error }}"
  nftables:
    path: "{{ rsyslog.nftables }}"
  fail2ban-actions:
    path: "{{ custom_logs.fail2ban }}"
  edgerouter:
    path: "{{ rsyslog.edgerouter }}"
  docker-events:
    path: "{{ custom_logs.container }}"
  service-state:
    path: "{{ custom_logs.services }}"
  ansible:
    path: "/home/{{ user }}/ansible/deployment.log"
  tg-success:
    path: "{{ custom_logs.telegram.success }}"
    config:
      when: daily
      rotate: 3
      size: 5M
