- name: Install fail2ban
  apt:
    name: fail2ban
    state: present

- name: Deploy jail.local
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: '0644'
  notify: restart fail2ban

- name: Deploy custom fail2ban actions
  copy:
    src: "action.d/{{ item }}"
    dest: "/etc/fail2ban/action.d/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  loop:
    - telegram.conf
    - sendmail-common.conf
  notify: restart fail2ban

- name: Create override dir
  file:
    path: /etc/systemd/system/fail2ban.service.d
    state: directory

- name: Deploy override
  template:
    src: override.conf.j2
    dest: /etc/systemd/system/fail2ban.service.d/override.conf
  notify:
    - daemon reload
    - restart fail2ban

- name: Enable and start fail2ban
  systemd:
    name: fail2ban
    enabled: yes
    state: started
