android_sshfs_devices: |
  {%- set devices = [] -%}

  {%- for name, host in ssh_hosts.items() -%}
    {%- if host.port is defined and (host.port | string) == (termux_port | string) -%}

      {%- set _ = devices.append({
        'name': name,
        'ip': host.hostname,
        'user': host.user,
        'key': host.identity,
        'mount': shares[name].mount
      }) -%}

    {%- endif -%}
  {%- endfor -%}

  {{ devices }}
