- name: daemon reload
  systemd:
    daemon_reload: yes

- name: restart docker
  systemd:
    name: docker
    state: restarted

- name: reload docker
  systemd:
    name: docker
    state: reloaded
