- name: Load values
  include_vars: "{{ item }}"
  with_fileglob:
    - defaults/*.yml

- name: Install smartmontools
  apt:
    name: smartmontools
    state: present

- name: Create prometheus directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
    mode: "0755"
  loop:
    - "{{ prometheus_base_dir }}"
    - "{{ prometheus_config_dir }}"
    - "{{ prometheus_data_dir }}"

- name: Create exporters directories
  file:
    path: "{{ exporters_dir }}"
    state: directory
    mode: "0755"

- name: Deploy prometheus config
  template:
    src: prometheus/prometheus.yml.j2
    dest: "{{ prometheus_config_dir }}/prometheus.yml"

- name: Deploy prometheus docker-compose
  template:
    src: prometheus/docker-compose.yml.j2
    dest: "{{ prometheus_base_dir }}/docker-compose.yml"

- name: Deploy exporters configs
  copy:
    src: "{{ item }}"
    dest: "{{ exporters_dir }}/{{ item | basename }}"
  with_fileglob:
    - templates/exporters/*.yml

- name: Deploy exporters docker-compose
  template:
    src: exporters/docker-compose.yml.j2
    dest: "{{ exporters_dir }}/docker-compose.yml"

- name: Run exporters containers
  community.docker.docker_compose_v2:
    project_src: "{{ exporters_dir }}"
    state: present

- name: Run prometheus container
  community.docker.docker_compose_v2:
    project_src: "{{ prometheus_base_dir }}"
    state: present
    recreate: always
