- name: Deploy systemd services
  copy:
    src: "{{ item }}"
    dest: "{{ systemd_services }}"
  with_fileglob:
    - "templates/systemd/*.service"
  notify: daemon reload

- name: Deploy templated systemd services
  template:
    src: "{{ item }}"
    dest: "{{ systemd_services }}/{{ item | basename | regex_replace('.j2','') }}"
  with_fileglob:
    - "templates/systemd/*.service.j2"
  notify: daemon reload

- name: Enable services
  systemd:
    name: "{{ item | basename | regex_replace('.j2','') | regex_replace('.service','') }}"
    enabled: yes
    state: started
  with_fileglob:
    - "templates/systemd/*.service"
    - "templates/systemd/*.service.j2"
