- name: Install dnsmasq
  apt:
    name: dnsmasq
    state: present
    update_cache: yes

- name: Deploy dnsmasq configs
  template:
    src: "{{ item }}"
    dest: "/etc/dnsmasq.d/{{ item | basename | regex_replace('.j2','') }}"
  with_fileglob:
    - templates/*.conf.j2
  notify: reload dnsmasq
