all:
  children:
    local:
      hosts:
        localhost:
          ansible_connection: local
    remote:
      hosts:
        nuc-server:
          # as in local ~/.ssh/config
          ansible_host: nuc
          ansible_user: "{{ user }}"

    server:
      children:
        local:
        remote:

    windows:
      hosts:
        asus:
          ansible_host: "{{ wireguard_devices.large_laptop.ip }}"
          ansible_user: "{{ whost.asus.user }}"
          ansible_password: "{{ vault_windows_asus_password }}"
        local-asus:
          ansible_host: "{{ lan_ip.large_laptop }}"
          ansible_user: "{{ whost.asus.user }}"
          ansible_password: "{{ vault_windows_asus_password }}"
        honor:
          ansible_host: "{{ wireguard_devices.laptop.ip }}"
          ansible_user: "{{ whost.honor.user }}"
          ansible_password: "{{ vault_windows_honor_password }}"
        local-honor:
          ansible_host: "{{ wireguard_devices.laptop.ip }}"
          ansible_user: "{{ whost.honor.user }}"
          ansible_password: "{{ vault_windows_honor_password }}"
