- name: Pull mihomo image
  community.docker.docker_image:
    name: metacubex/mihomo
    tag: latest
    source: pull

- name: Run mihomo container
  community.docker.docker_container:
    name: "{{ docker.mihomo.name }}"
    image: metacubex/mihomo:latest
    restart_policy: unless-stopped
    recreate: true
    restart: true
    ports:
      - "{{ docker.mihomo.port.mixed }}:{{ docker.mihomo.port.mixed }}"
      - "{{ docker.mihomo.port.socks5 }}:{{ docker.mihomo.port.socks5 }}"
    volumes:
      - "{{ clash_config_dir }}:/root/.config/mihomo"
    stop_timeout: 30
