bad_bot:
  - sqlmap
  - nikto
  - acunetix
  - dirbuster
  - gobuster
  - feroxbuster
  - masscan
  - nmap
  - zmap
  - zgrab
  - ffuf
  - dirsearch
  - wpscan

bad_bot_regex: "{{ bad_bot | join('|') }}"

tarpit:
  - \.php
  - \.env
  - \.git
  - \.sql
  - \.bak
  - \.old
  - \.aws
  - \.ssh
  - \.kube
  - \.docker
  - \.htaccess
  - wp-admin
  - wp-login
  - xmlrpc
  - phpmyadmin
  - id_rsa
  - vendor
  - wget
  - curl
  - composer\.json

tarpit_regex: "{{ tarpit | join('|') }}"