- name: Read profile.yaml
  ansible.windows.slurp:
    path: "{{ ansible_env.USERPROFILE }}\\AppData\\Roaming\\{{ clash_meta_client }}\\profile.yaml"
  register: clash_profile

- name: Extract current id
  set_fact:
    clash_id: "{{ (clash_profile.content | b64decode | from_yaml).current }}"

- name: Read remote rules before deploy
  ansible.windows.slurp:
    path: "{{ ansible_env.USERPROFILE }}\\AppData\\Roaming\\{{ clash_meta_client }}\\rules\\{{ clash_id }}.yaml"
  register: before_rules
  ignore_errors: true

- name: Render rules template
  set_fact:
    rendered_rules: "{{ lookup('template', 'templates/rules.yaml.j2') }}"

# - name: Show clean unified rules diff
#   delegate_to: localhost
#   changed_when: false
#   when: before_rules is defined and before_rules.content is defined
#   vars:
#     before: "{{ before_rules.content | b64decode | from_yaml | to_nice_json }}"
#     after: "{{ rendered_rules | from_yaml | to_nice_json }}"
#   shell: |
#     python3 - << 'EOF'
#     import difflib
#
#     before = """{{ before | replace('"', '\\"') }}""".splitlines()
#     after = """{{ after | replace('"', '\\"') }}""".splitlines()
#
#     diff = list(difflib.unified_diff(
#         before, after,
#         fromfile='before',
#         tofile='after',
#         lineterm=''
#     ))
#
#     if diff:
#         print('\n'.join(diff))
#     EOF

- name: Show unified rules diff 
  delegate_to: localhost
  vars:
    before: "{{ before_rules.content | b64decode }}"
    after: "{{ rendered_rules }}"
  shell: |
    python3 - << 'EOF'
    import difflib

    before = """{{ before | replace('"', '\\"') }}""".splitlines()
    after = """{{ after | replace('"', '\\"') }}""".splitlines()

    for line in difflib.unified_diff(before, after, lineterm=''):
        print(line)
    EOF

- name: Deploy clash custom rules
  win_template:
    src: templates/rules.yaml.j2
    dest: "{{ ansible_env.USERPROFILE }}\\AppData\\Roaming\\{{ clash_meta_client }}\\rules\\{{ clash_id }}.yaml"

- name: Read remote config before deploy
  ansible.windows.slurp:
    path: "{{ ansible_env.USERPROFILE }}\\AppData\\Roaming\\{{ clash_meta_client }}\\mihomo.yaml"
  register: before_config
  ignore_errors: true

- name: Render config template
  set_fact:
    rendered_config: "{{ lookup('template', 'templates/mihomo.yaml.j2') }}"

# - name: Show clean unified config diff
#   delegate_to: localhost
#   changed_when: false
#   when: before_config is defined and before_config.content is defined
#   vars:
#     before: "{{ before_config.content | b64decode | from_yaml | to_nice_json }}"
#     after: "{{ rendered_config | from_yaml | to_nice_json }}"
#   shell: |
#     python3 - << 'EOF'
#     import difflib
#
#     before = """{{ before | replace('"', '\\"') }}""".splitlines()
#     after = """{{ after | replace('"', '\\"') }}""".splitlines()
#
#     diff = list(difflib.unified_diff(
#         before, after,
#         fromfile='before',
#         tofile='after',
#         lineterm=''
#     ))
#
#     if diff:
#         print('\n'.join(diff))
#     EOF

- name: Show unified config diff
  delegate_to: localhost
  vars:
    before: "{{ before_config.content | b64decode }}"
    after: "{{ rendered_config }}"
  shell: |
    python3 - << 'EOF'
    import difflib

    before = """{{ before | replace('"', '\\"') }}""".splitlines()
    after = """{{ after | replace('"', '\\"') }}""".splitlines()

    for line in difflib.unified_diff(before, after, lineterm=''):
        print(line)
    EOF

- name: Deploy mihomo config
  win_template:
    src: templates/mihomo.yaml.j2
    dest: "{{ ansible_env.USERPROFILE }}\\AppData\\Roaming\\{{ clash_meta_client }}\\mihomo.yaml"
