- name: Read profile.yaml
  ansible.windows.slurp:
    path: "{{ ansible_env.USERPROFILE }}\\AppData\\Roaming\\{{ clash_meta_client }}\\profile.yaml"
  register: clash_profile

- name: Extract current id
  set_fact:
    clash_id: "{{ (clash_profile.content | b64decode | from_yaml).current }}"

- name: Deploy clash custom rules
  win_template:
    src: templates/rules.yaml.j2
    dest: "{{ ansible_env.USERPROFILE }}\\AppData\\Roaming\\{{ clash_meta_client }}\\rules\\{{ clash_id }}.yaml"

- name: Deploy mihomo config
  win_template:
    src: templates/mihomo.yaml.j2
    dest: "{{ ansible_env.USERPROFILE }}\\AppData\\Roaming\\{{ clash_meta_client }}\\mihomo.yaml"
