- name: Install base packages
  apt:
    name:
      - git
      - curl
      - jq
      - tree
      - bat
      - far2l
      - tcpdump
      - rsync
      - ca-certificates
      - unattended-upgrades
    state: present
    update_cache: yes

- name: Bat settings
  copy:
    content: |
      --style=plain
      --paging=never
    dest: /home/{{ user }}/.config/bat/config

