### wsl
- name: Create custom VSCode tasks directory in HOME workspace
  file:
    path: "{{ homedir }}/.vscode"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0755'

- name: Deploy VSCode task enabling 'tools/j2render.sh'
  template:
    src: tasks.json.j2
    dest: "{{ homedir }}/.vscode/tasks.json"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0644'

### windows (delegated)
- name: Resolve current Windows host alias
  set_fact:
    windows_target_host: >-
      {{
        whost
        | dict2items
        | selectattr('value.name', 'equalto', ansible_hostname)
        | map(attribute='value.host')
        | first
      }}

# - name: Gather Windows facts
#   ansible.windows.setup:
#   delegate_to: "{{ windows_target_host }}"
#   delegate_facts: true

- name: Deploy VSCode task keybinding to run 'tools/j2render.sh'
  win_copy:
    src: keybindings.json
    # dest: "{{ ansible_facts.env.APPDATA }}\\Roaming\\Code\\User\\keybindings.json"
    # dest: "{{ hostvars[windows_target_host].ansible_env.APPDATA }}\\Roaming\\Code\\User\\keybindings.json"
    dest: "{{ hostvars[windows_target_host].ansible_facts.env.APPDATA }}\\Roaming\\Code\\User\\keybindings.json"
  delegate_to: "{{ windows_target_host }}"
