stack_base_dir: /opt/log_monitoring
stack_config_dir: "{{ stack_base_dir }}/config"

loki_data_dir: "{{ stack_base_dir }}/data"

promtail_version: "2.9.5"

promtail_dir: "{{ stack_base_dir }}/promtail"
geoip_plugin: "{{ promtail_dir }}/GeoLite2-City.mmdb"
container_geoip_plugin: /etc/promtail/GeoLite2-City.mmdb
