- name: Read remote config before deploy
  ansible.windows.slurp:
    path: "{{ ansible_facts.env.USERPROFILE }}\\.wezterm.lua"
  register: before_config
  ignore_errors: true

- name: Render repo config
  set_fact:
    rendered_config: "{{ lookup('template', 'templates/wezterm.lua.j2') }}"

- name: Show config unified diff 
  delegate_to: localhost
  vars:
    before: "{{ before_config.content | b64decode }}"
    after: "{{ rendered_config }}"
  shell: |
    {{ lookup('template', '../templates/pyshell.sh.j2') }}
  ignore_errors: true

- name: Deploy config
  win_template:
    src: templates/wezterm.lua.j2
    dest: "{{ ansible_facts.env.USERPROFILE }}\\.wezterm.lua"

- name: Create configuration modules dir
  win_file:
    path: "{{ ansible_facts.env.ProgramFiles }}\\{{ wezterm_modules_path }}"
    state: directory

- include_tasks: plugins.yml
  loop: "{{ wezterm_modules }}"
