- name: "{{ item }} : Read remote config before deploy"
  ansible.windows.slurp:
    path: "{{ ansible_facts.env.ProgramFiles }}\\{{ wezterm_modules_path }}\\{{ item }}.lua"
  register: before_config
  ignore_errors: true

- name: "{{ item }} : Render repo config"
  set_fact:
    rendered_config: "{{ lookup('file', 'files/' ~ item ~ '.lua') }}"

- name: "{{ item }} : Show config unified diff"
  delegate_to: localhost
  vars:
    before: "{{ before_config.content | b64decode }}"
    after: "{{ rendered_config }}"
  shell: |
    {{ lookup('template', '../templates/pyshell.sh.j2') }}
  ignore_errors: true

- name: "{{ item }} : Deploy config"
  win_copy:
    src: files/{{ item }}.lua
    dest: "{{ ansible_facts.env.ProgramFiles }}\\{{ wezterm_modules_path }}\\{{ item }}.lua"
