- hosts: localhost
  connection: local
  become: false
  # gather_facts: false
  gather_subset:
    - min

  tasks:
    - name: Load all role defaults recursively
      include_vars:
        dir: "{{ playbook_dir + '/../' + roles_dir + '/' + role_name }}/defaults"
        extensions: ["yml"]
      failed_when: false
      tags: [always]

    # which are marked with 'tags: [vars]'
    - name: Run only variable-setting tasks (set_fact/include_vars) from the target role
      include_role:
        name: "{{ playbook_dir }}/../{{ roles_dir }}/{{ role_name }}"
        tasks_from: main.yml
      tags: [always]

    # - name: Render template
    #   copy:
    #     content: "{{ lookup('template', playbook_dir + '/../' + template_path) }}"
    #     dest: "{{ output_path }}"
    #   tags: [always]

    - name: Render template
      template:
        src: "{{ playbook_dir }}/../{{ template_path }}"
        dest: "{{ output_path }}"
      tags: [always]
