[main]
font=JetBrainsMono Nerd Font:size=12
dpi-aware=yes

# https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/wezterm/Hurtado.toml
[colors]
foreground=dbdbdb
background=000000

regular0=575757
regular1=d51d00
regular2=a5de54
regular3=fbe84a
regular4=496487
regular5=c001c1
regular6=86eafe
regular7=dbdbdb

bright0=404040
bright1=ff1b00
bright2=a5e055
bright3=fbe74a
bright4=89beff
bright5=fd5ff1
bright6=86e9fe
bright7=cbcdcb

[cursor]
style=block
