### https://man.archlinux.org/man/extra/kmscon/kmscon.conf.5.en ### man kmscon
font-engine=freetype
font-name=JetBrainsMono NF
font-size=14

### Video Options ###
render-engine=gltex
# drm
bbulk
soft-cursor

### Input Options ###
mouse
no-backspace-delete

palette=custom
# https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/wezterm/Hurtado.toml
palette-black=87,87,87
palette-red=255,27,0
palette-green=165,224,85
palette-yellow=251,231,74
palette-blue=73,100,135
palette-magenta=253,95,241
palette-cyan=134,233,254
palette-light-grey=203,204,203
palette-dark-grey=64,64,64
palette-light-red=213,29,0
palette-light-green=165,223,85
palette-light-yellow=251,232,74
palette-light-blue=137,190,255
palette-light-magenta=192,1,193
palette-light-cyan=134,234,254
palette-white=219,219,219
palette-foreground=219,219,219
palette-background=0,0,0
