tarpit:
  - \.php
  - \.env
  - \.git
  - \.gitconfig
  - \.sql
  - \.bak
  - \.old
  - \.aws
  - \.ssh
  - \.svn
  - \.kube
  - \.docker
  - \.htaccess
  - \.DS_Store
  - \.go
  - \.yml
  - \.yaml
  - \.xml
  - \.toml
  - \.json
  - \.tfstate
  - \.tfvars
  - \.tfrc
  - \.pgpass
  - \.netrc
  - \.key
  - \.local
  - \.s3cfg
  - \.ini
  - \.zip
  - \.tar
  - \.pypirc
  - \.well-known/(?!acme-challenge)
  - wp-admin
  - wp-login
  - wp-config
  - wordpress
  - xmlrpc
  - aws_credentials
  - phpmyadmin
  - phpunit
  - phpinfo
  - docker
  - docker-compose
  - backup
  - id_rsa
  - login
  - vendor
  - wget
  - curl
  - owa
  - ecp
  - jdni
  - evox
  - sdk
  - nmap
  - cgi-bin
  - dns-query
  - autodiscover
  - powershell
  - actuator
  - exchange
  - adminer
  - boaform
  - swagger
  - graphql
  - gql
  - telescope
  - webjars
  - microsoft.exchange
  - composer\.json
  - 'ldap://'
  - 'rmi://'
  - 'dns://'
  - HNAP1
  - MGLNDD
  - LEAKIX
  - ReportServer
  - developmentserver
  - metadatauploader
  - onvif
  - ssdpcgi
  - ignition
  - sitemap
  - blog
  - kontakty
  - contact
  - about
  - txets
  - terraform
  - firebase
  - sendgrid
  - heapdump
  - configprops
  - credentials
  - appsettings
