- name: Create common configs directory
  file:
    path: "{{ stack_config_dir }}"
    state: directory

- name: Create Loki directories
  file:
    path: "{{ item }}"
    state: directory
    owner: 10001
    group: 10001
    mode: "0755"
  loop:
    - "{{ loki_data_dir }}"
    - "{{ loki_data_dir }}/chunks"
    - "{{ loki_data_dir }}/index"
    - "{{ loki_data_dir }}/tsdb-shipper-cache"

- name: Deploy docker-compose
  template:
    src: docker-compose.yml.j2
    dest: "{{ stack_base_dir }}/docker-compose.yml"

- name: Deploy Loki config
  template:
    src: loki-config.yml.j2
    dest: "{{ stack_config_dir }}/loki.yml"

- name: Deploy Promtail config
  template:
    src: promtail-config.yml.j2
    dest: "{{ stack_config_dir }}/promtail.yml"

- name: Run Loki stack
  community.docker.docker_compose_v2:
    project_src: "{{ stack_base_dir }}"
    state: present
    recreate: always

- name: Check Loki container running status
  uri:
    url: "http://{{ localhost }}:{{ loki_port }}/ready"
    status_code: [200, 204]
  register: result
  retries: 5
  delay: 3
  until: result.status in [200, 204]

- name: Get Promtail container info
  community.docker.docker_container_info:
    name: "{{ promtail_container }}"
  register: promtail_info

- name: Fail if Promtail is not running
  fail:
    msg: "Promtail container is not running"
  when: not promtail_info.container.State.Running
