- name: Load values
  include_vars: "{{ item }}"
  with_fileglob:
    - defaults/promtail_labels/*.yml

- name: Create Loki directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ loki_user }}"
    group: "{{ loki_user }}"
    mode: "0755"
  loop:
    - "{{ loki_dir }}"
    - "{{ loki_data_dir }}"
    - "{{ loki_data_dir }}/chunks"
    - "{{ loki_data_dir }}/compactor"
    - "{{ loki_data_dir }}/index"
    - "{{ loki_data_dir }}/tsdb-shipper-active"
    - "{{ loki_data_dir }}/tsdb-shipper-cache"
    - "{{ loki_data_dir }}/wal"

- name: Create Promtail directory
  file:
    path: "{{ promtail_dir }}"
    state: directory

- name: Deploy Loki docker-compose
  template:
    src: loki/docker-compose.yml.j2
    dest: "{{ loki_dir }}/docker-compose.yml"

- name: Deploy Promtail docker-compose
  template:
    src: promtail/docker-compose.yml.j2
    dest: "{{ promtail_dir }}/docker-compose.yml"

- name: Deploy Loki config
  template:
    src: loki/config.yml.j2
    dest: "{{ loki_dir }}/loki.yml"

- name: Deploy Promtail config
  template:
    src: promtail/config.yml.j2
    dest: "{{ promtail_dir }}/promtail.yml"

- name: Download MaxMind DB
  get_url:
    url: "https://github.com/P3TERX/GeoLite.mmdb/raw/download/GeoLite2-City.mmdb"
    dest: "{{ geoip_plugin }}"
    mode: '0644'

- name: Run Loki container
  community.docker.docker_compose_v2:
    project_src: "{{ loki_dir }}"
    state: present

- name: Run Promtail container
  community.docker.docker_compose_v2:
    project_src: "{{ promtail_dir }}"
    state: present
    recreate: always

- name: Check Loki container running status
  uri:
    url: "http://{{ localhost }}:{{ loki_port }}/ready"
    status_code: [200, 204]
  register: result
  retries: 5
  delay: 3
  until: result.status in [200, 204]

- name: Get Promtail container info
  community.docker.docker_container_info:
    name: "{{ docker.promtail }}"
  register: promtail_info

- name: Fail if Promtail is not running
  fail:
    msg: "Promtail container is not running"
  when: not promtail_info.container.State.Running
