- name: Create main directory
  file:
    path: /opt/log_monitoring
    state: directory

- name: Create configs directory
  file:
    path: /opt/log_monitoring/config
    state: directory

- name: Deploy docker-compose
  template:
    src: docker-compose.yml.j2
    dest: /opt/log_monitoring/docker-compose.yml

- name: Deploy Loki config
  template:
    src: loki-config.yml.j2
    dest: /opt/log_monitoring/config/loki.yml

- name: Deploy Promtail config
  template:
    src: promtail-config.yml.j2
    dest: /opt/log_monitoring/config/promtail.yml

- name: Run Loki stack
  community.docker.docker_compose_v2:
    project_src: /opt/log_monitoring
    state: present

- name: Check Loki container running status
  uri:
    url: "http://127.0.0.1:{{ loki_port }}"
    status_code: 200
  register: result
  retries: 5
  delay: 3
  until: result.status == 200

- name: Get Promtail container info
  community.docker.docker_container_info:
    name: log_monitoring-promtail-1
  register: promtail_info

- name: Fail if Promtail is not running
  fail:
    msg: "Promtail container is not running"
  when: not promtail_info.container.State.Running
