- name: Run Loki and Promtail containers
  block:
    - name: Start docker compose
      community.docker.docker_compose_v2:
        project_src: "{{ stack_base_dir }}"
        state: present
        recreate: always
  rescue:
    - name: Restart docker
      service:
        name: docker
        state: restarted
    - name: Wait for docker
      wait_for:
        timeout: 10
    - name: Retry docker compose
      community.docker.docker_compose_v2:
        project_src: "{{ stack_base_dir }}"
        state: present
        recreate: always
