- import_tasks: appimage.yml #2.8.0
# - import_tasks: brew.yml #2.8.0 with less plugins
# - import_tasks: fork.yml #2.7.0 has lua plugins but bugged as apt 2.6.0 version

- name: Deploy settings configs for user
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_facts.env.SUDO_HOME }}/{{ far2l_configdir }}/"
    mode: '0644'
  with_fileglob:
    - "files/*.ini"

- name: Configure settings
  lineinfile:
    path: "{{ ansible_facts.env.SUDO_HOME }}/{{ far2l_configdir }}/config.ini"
    regexp: '{{ item.regex }}'
    line: '{{ item.replace }}'
  loop: "{{ config_replacements }}"

- name: Change default theme to Hercules Night
  lineinfile:
    path: "{{ ansible_facts.env.SUDO_HOME }}/{{ far2l_configdir }}/colors.ini"
    regexp: 'CurrentTheme=(.*)'
    line: 'CurrentTheme=Hercules Night'

- name: Create root far2l configs symlink
  file:
    src: "{{ ansible_facts.env.SUDO_HOME }}/{{ far2l_configdir }}"
    dest: "{{ ansible_facts.env.HOME }}/{{ far2l_configdir }}"
    state: link
