- name: Clone original repo
  become_user: "{{ user }}"
  git:
    repo: https://github.com/elfmz/far2l
    dest: "/home/{{ user }}/far2l"

- name: Clone forked repo with luamacro
  become_user: "{{ user }}"
  git:
    repo: https://github.com/shmuz/far2m
    dest: "/home/{{ user }}/far2m"
