- hosts: server
  gather_subset:
    - min

  pre_tasks:
    - name: Check the server by hostname
      assert:
        that: ansible_facts.hostname == "nuc-server"
        fail_msg: "This playbook is supposed to be run only on the server"
    - name: Fail if unknown tag is used
      tags: always
      assert:
        that: ansible_run_tags | difference(valid_tags + ['all']) | length == 0
        fail_msg: "Unknown tag used: {{ ansible_run_tags | difference(valid_tags + ['all']) }}"
      vars:
        valid_tags: "{{ roles_list + includes_list }}"

  vars:
    includes_list:
      - base
      - sshcli
      - zsh
    roles_list:
      - etckeeper
      - auditd
      - sysctl
      - sshd
      - wireguard
      - firewall
      - nginx
      - fail2ban
      - crowdsec
      - dnsmasq
      - rsyslog
      - letsencrypt
      - logrotate
      - samba
      - mounts
      - mount_android
      - certificates
      - mail_sender
      - mihomo
      # - notifications
      - cockpit
      - far2l
      - neovim
      - docker
      - nginx_auth
      - docker_network
      - loki
      - promtail
      - wgdashboard
      - prometheus
      - grafana
      - guacamole
      - actual

  tasks:
    - name: Include common linux roles
      include_role:
        name: "{{ included_item }}"
        apply:
          tags: "{{ included_item }}"
      loop: "{{ includes_list }}"
      loop_control:
        loop_var: included_item
      tags:
        - always
    - name: Include server roles dynamically
      include_role:
        name: "{{ role_item }}"
        apply:
          tags: "{{ role_item }}"
      loop: "{{ roles_list }}"
      loop_control:
        loop_var: role_item
      tags:
        - always
