clash_dns_enabled: false
clash_dns_nameservers:
  - 1.1.1.1
  - 8.8.8.8
clash_dns_fake_ip_filter:
  - "*.lan"
  - stun.*.*.*
  - stun.*.*
  - time.windows.com
  - time.nist.gov
  - time.apple.com
  - time.asia.apple.com
  - "*.openwrt.pool.ntp.org"
  - pool.ntp.org
  - ntp.ubuntu.com
  - time1.apple.com
  - time2.apple.com
  - time3.apple.com
  - time4.apple.com
  - time5.apple.com
  - time6.apple.com
  - time7.apple.com
  - time1.google.com
  - time2.google.com
  - time3.google.com
  - time4.google.com
  - api.joox.com
  - joox.com
  - "*.xiami.com"
  - "*.msftconnecttest.com"
  - "*.msftncsi.com"
  - +.xboxlive.com
  - "*.*.stun.playstation.net"
  - xbox.*.*.microsoft.com
  - "*.ipv6.microsoft.com"
  - speedtest.cros.wr.pvp.net
