clash_proxy_mode: rule
#clash_proxy_mode: rule, global, direct
clash_web_port: 9091

clash_connection_type: url-test
#clash_connection_type: select, fallback, url-test
clash_connection_interval: 30
clash_connection_tolerance: 100

clash_rules:
  - DOMAIN-SUFFIX,telegram.org,→ Remnawave
  - MATCH,DIRECT
