[Definition]

actionban = nft add element inet filter blacklist { <ip> timeout <bantime> }
actionunban = nft delete element inet filter blacklist { <ip> }
actioncheck = nft list set inet filter blacklist