[Definition]

table_family = inet
table=filter
addr_set=permanent_blacklist

actionban = nft add element <table_family> <table> <addr_set> \{ <ip> \}
actionunban =
actioncheck = nft list set <table_family> <table> <addr_set>