[Definition]

actionban = /usr/local/bin/tgbot_notify.sh "<b><name></b>: banned <ip> from <fq-hostname>
            failures: <failures>
            ipfailures: <ipfailures>
            ipjailfailures: <ipjailfailures>
            <pre>$(curl -s http://ip-api.com/json/<ip> | jq)</pre>
            <pre>$(grep -m 20 -wF <ip> <logpath> | grep -v " sudo: " | tail -n 20)</pre>"
actionunban = /usr/local/bin/tgbot_notify.sh "<b><name></b>: unbanned <ip> from <fq-hostname>"

[Init]
name = telegram
