blacklist_asn_ids:
#Microsoft Azure Cloud
  - 8075
#DigitalOcean
  - 14061
#Alibaba Cloud
  - 45102
#Telegram Messenger
  - 62041
#Tcloudnet
  - 399077
#Tencent
  - 132203
#Byteplus
  - 150436
#Proton66
  - 198953

blacklist_asn_names:
  - Alibaba
  - DigitalOcean
  - Telegram Messenger
  - Tcloudnet
  - Tencent
  - Byteplus
  - Proton66