- name: Load variables
  include_vars: "{{ item }}"
  with_fileglob:
    - defaults/*.yml

- name: Install required packages
  apt:
    name:
    - npm
    - cargo
    - golang-go
    - cmake
    - ripgrep
    - fd-find
    state: present

- name: Install required packages via npm
  npm:
    name: tree-sitter-cli
    global: true
    state: present

- name: Install neovim from git repo
  get_url:
    url: https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.appimage
    dest: /usr/local/bin/nvim
    mode: '0777'

- name: Install lazy.nvim plugin package manager
  git:
    repo: https://github.com/folke/lazy.nvim
    dest: "/{{ item }}/.local/share/nvim/lazy/lazy.nvim"
  loop:
    - "home/{{ user }}"
    - root

- name: Create config directories for default user
  file:
    path: "/home/{{ user }}/{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0775'
  loop:
    - .config/nvim/lua/config
    - .config/nvim/lua/plugins

- name: Create config directories for root
  file:
    path: "/root/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - .config/nvim/lua/config
    - .config/nvim/lua/plugins

- name: Deploy init.lua
  copy:
    src: templates/init.lua
    dest: "/{{ item }}/.config/nvim"
    mode: '0664'
  loop:
    - "home/{{ user }}"
    - root

- name: Deploy plugins.lua
  copy:
    src: templates/lua/plugins.lua
    dest: "/{{ item }}/.config/nvim/lua"
    mode: '0664'
  loop:
    - "home/{{ user }}"
    - root

- name: Deploy plugin configurations for default user
  copy:
    src: "{{ item }}"
    dest: "/home/{{ user }}/.config/nvim/lua/plugins"
    mode: '0664'
  with_fileglob:
    - "templates/lua/plugins/*.lua"

- name: Deploy plugin configurations for root
  copy:
    src: "{{ item }}"
    dest: /root/.config/nvim/lua/plugins
    mode: '0664'
  with_fileglob:
    - "templates/lua/plugins/*.lua"

- name: Deploy templated plugin configurations for default user
  template:
    src: "{{ item }}"
    dest: "/home/{{ user }}/.config/nvim/lua/plugins/{{ item | basename | regex_replace('.j2','') }}"
    mode: '0664'
  with_fileglob:
    - "templates/lua/plugins/*.lua.j2"

- name: Deploy templated plugin configurations for root
  template:
    src: "{{ item }}"
    dest: "/root/.config/nvim/lua/plugins/{{ item | basename | regex_replace('.j2','') }}"
    mode: '0664'
  with_fileglob:
    - "templates/lua/plugins/*.lua.j2"

- name: Deploy lua configs for default user
  copy:
    src: "{{ item }}"
    dest: "/home/{{ user }}/.config/nvim/lua/config"
    mode: '0664'
  with_fileglob:
    - "templates/lua/config/*.lua"

- name: Deploy lua configs for root
  copy:
    src: "{{ item }}"
    dest: /root/.config/nvim/lua/config
    mode: '0664'
  with_fileglob:
    - "templates/lua/config/*.lua"

- name: Deploy templated lua configs for default user
  template:
    src: "{{ item }}"
    dest: "/home/{{ user }}/.config/nvim/lua/config/{{ item | basename | regex_replace('.j2','') }}"
    mode: '0664'
  with_fileglob:
    - "templates/lua/config/*.lua.j2"

- name: Deploy templated lua configs for root
  template:
    src: "{{ item }}"
    dest: "/root/.config/nvim/lua/config/{{ item | basename | regex_replace('.j2','') }}"
    mode: '0664'
  with_fileglob:
    - "templates/lua/config/*.lua.j2"

- name: Synchronize lazy.nvim plugins for default user
  become_user: "{{ user }}"
  command: nvim --headless "+Lazy! sync" +qa
  environment:
    HOME: "/home/{{ user }}"

- name: Synchronize lazy.nvim plugins for root
  become_user: root
  command: nvim --headless "+Lazy! sync" +qa
  environment:
    HOME: "/root"

- name: Install Treesitter parsers for default user
  become_user: "{{ user }}"
  command: nvim --headless "+TSUpdate" +qa
  environment:
    HOME: "/home/{{ user }}"
  # command: nvim --headless "+TSInstall {{ treesitter | join(' ') }}" +qa
- name: Install Treesitter parsers for root
  become_user: root
  command: nvim --headless "+TSUpdate" +qa
  environment:
    HOME: "/root"

- name: Install LSP servers for default user
  become_user: "{{ user }}"
  command: nvim --headless "+MasonInstall {{ mason_install | join(' ') }}" +qa
  environment:
    HOME: "/home/{{ user }}"
  # command: nvim --headless "+MasonInstall {{ mason_lspconfig | map(attribute='mason') | join(' ') }}" +qa
    # command: nvim --headless "+MasonInstall {{ item }}" +qa
    # loop: "{{ mason_lspconfig | map(attribute='mason') }}"
- name: Install LSP servers for root
  become_user: root
  command: nvim --headless "+MasonInstall {{ mason_install | join(' ') }}" +qa
  environment:
    HOME: "/root"
