- name: Load variables
  include_vars: "{{ item }}"
  with_fileglob:
    - defaults/*.yml

- name: Install required packages
  apt:
    name:
    - npm
    - cargo
    - golang-go
    - cmake
    - ripgrep
    - fd-find
    state: present

- name: Install required packages via npm
  npm:
    name: tree-sitter-cli
    global: true
    state: present

# - name: Install neovim from git repo
#   get_url:
#     url: https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.appimage
#     dest: "{{ neovim }}"
#     mode: '0777'

- name: Install lazy.nvim plugin package manager
  git:
    repo: https://github.com/folke/lazy.nvim
    dest: "{{ ansible_env.SUDO_HOME }}/{{ nvimdir.share }}/lazy/lazy.nvim"

- name: Create config directories
  file:
    path: "{{ ansible_env.SUDO_HOME }}/{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0775'
  loop:
    - "{{ nvimdir.config }}/lua/config"
    - "{{ nvimdir.config }}/lua/plugins"

- name: Ensure required root directories exist
  file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: directory
  loop:
    - "{{ nvimdir.share | dirname }}"

- name: Deploy init.lua
  copy:
    src: templates/init.lua
    dest: "{{ ansible_env.SUDO_HOME }}/{{ nvimdir.config }}"
    mode: '0664'

- name: Deploy plugins.lua
  copy:
    src: templates/lua/plugins.lua
    dest: "{{ ansible_env.SUDO_HOME }}/{{ nvimdir.config }}/lua"
    mode: '0664'

- name: Deploy plugin configurations
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.SUDO_HOME }}/{{ nvimdir.config }}/lua/plugins"
    mode: '0664'
  with_fileglob:
    - "templates/lua/plugins/*.lua"

- name: Deploy templated plugin configurations
  template:
    src: "{{ item }}"
    dest: "{{ ansible_env.SUDO_HOME }}/{{ nvimdir.config }}/lua/plugins/{{ item | basename | regex_replace('.j2','') }}"
    mode: '0664'
  with_fileglob:
    - "templates/lua/plugins/*.lua.j2"

- name: Deploy lua configs
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.SUDO_HOME }}/{{ nvimdir.config }}/lua/config"
    mode: '0664'
  with_fileglob:
    - "templates/lua/config/*.lua"

- name: Deploy templated lua configs
  template:
    src: "{{ item }}"
    dest: "{{ ansible_env.SUDO_HOME }}/{{ nvimdir.config }}/lua/config/{{ item | basename | regex_replace('.j2','') }}"
    mode: '0664'
  with_fileglob:
    - "templates/lua/config/*.lua.j2"

- name: Synchronize lazy.nvim plugins
  become_user: "{{ user }}"
  command: nvim --headless "+Lazy! sync" +qa
  environment:
    HOME: "{{ ansible_env.SUDO_HOME }}"

- name: Install Treesitter parsers
  become_user: "{{ user }}"
  command: nvim --headless "+TSUpdate" +qa
  environment:
    HOME: "{{ ansible_env.SUDO_HOME }}"
  # command: nvim --headless "+TSInstall {{ treesitter | join(' ') }}" +qa

- name: Install LSP servers
  become_user: "{{ user }}"
  command: nvim --headless "+MasonInstall {{ mason_install | join(' ') }}" +qa
  environment:
    HOME: "{{ ansible_env.SUDO_HOME }}"
  # command: nvim --headless "+MasonInstall {{ mason_lspconfig | map(attribute='mason') | join(' ') }}" +qa
    # command: nvim --headless "+MasonInstall {{ item }}" +qa
    # loop: "{{ mason_lspconfig | map(attribute='mason') }}"

- name: Create root nvim configs symlink
  file:
    src: "{{ ansible_env.SUDO_HOME }}/{{ nvimdir.config }}"
    dest: "{{ ansible_env.HOME }}/{{ nvimdir.config }}"
    state: link

- name: Create root nvim shares symlink
  file:
    src: "{{ ansible_env.SUDO_HOME }}/{{ nvimdir.share }}"
    dest: "{{ ansible_env.HOME }}/{{ nvimdir.share }}"
    state: link

- name: Set nvim as default sudoeditor
  become_user: root
  command: update-alternatives --install /usr/bin/sudoedit sudoedit {{ neovim }} 50
