- name: Install WireGuard
  apt:
    name: wireguard
    state: present

- name: Deploy config
  template:
    src: {{ wireguard_interface }}.conf.j2
    dest: /etc/wireguard/{{ wireguard_interface }}.conf
    mode: '0600'
  notify: restart wg

- name: Enable service
  systemd:
    name: wg-quick@{{ wireguard_interface }}
    enabled: yes
    state: started
