fail2ban_ignoreip:
  - "{{ home_ip }}"
  - "{{ server_lan_ip }}"

fail2ban_bantime: 3h
fail2ban_bantime_increment: true
fail2ban_bantime_factor: 2
fail2ban_bantime_max: 1week
fail2ban_findtime: 10m
fail2ban_maxretry: 1
fail2ban_backend: systemd
fail2ban_actionstart_on_demand: true
fail2ban_action:
  - nftables-tempoban
  - telegram

fail2ban_jails:
  - name: sshd
    enabled: true
    port: "{{ sshd_port }}"

  - name: nginx-http-auth
    enabled: true
    logpath: /var/log/nginx/*access.log

  - name: nginx-botsearch
    enabled: true
    logpath: /var/log/nginx/*access.log

  - name: nginx-badbots
    enabled: true
    logpath: /var/log/nginx/*access.log

  - name: nginx-noscript
    enabled: true
    logpath: /var/log/nginx/*access.log

  - name: nginx-404-scan
    enabled: true
    logpath: /var/log/nginx/*access.log
    maxretry: 20
    findtime: 1m
    bantime: 1h

  - name: nginx-limit-req
    enabled: true
    logpath: /var/log/nginx/*access.log
    maxretry: 10
    findtime: 10m
    bantime: 1h

  - name: recidive
    enabled: true
    logpath: /var/log/fail2ban.log
    backend: auto
    bantime: 1month
    findtime: 1d
    maxretry: 1
    action:
      - nftables-permaban
      - telegram
